### ISSUE TITLE
Handling of @type in Expansion Algorithm

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#100]
The [Expansion Algorithm](https://w3c.github.io/json-ld-api/#expansion-algorithms) item 11.1 says:

> For each term which is a value of value ordered lexicographically

The wording "a value of value" is unclear here. By context, I *believe* it means something similar to looping over:

* each element of `value` if `value` is an array
* the single item `value` otherwise

If that is the correct interpretation, wording to this effect would be very helpful. Alternatively, 11.1 might be preceded by language (similar to that used elsewhere in the document) that ensures that `value` is an array before 11.1 is reached.

Beyond the "value of value" wording, 11.1 seems to have an implicit assumption that `value` is either a string, or an array of strings. This is made explicit in 13.4.4 (which may include other expanded `@type` values introduced in the intervening steps) where a `invalid type value` error can be detected. If this restriction was also enforced in 11, it might have the added benefit of adding language that could ensure `value` was an array before 11.1 was reached.

FWIW, the JSON-LD playground seems to suggest that a *third* possible value for a `@type` key is an empty object:

> jsonld.SyntaxError: Invalid JSON-LD syntax; "@type" value must a string, an array of strings, or an empty object.

**Comment by gkellogg** [comment]
> The [Expansion Algorithm](https://w3c.github.io/json-ld-api/#expansion-algorithms) item 11.1 says:
> 
> > For each term which is a value of value ordered lexicographically
> 
> The wording "a value of value" is unclear here.

There are a number of cases where we talk about something which may be both a defined item or colloquial idiom such as "value" and refer to a similarly named variable.

> By context, I _believe_ it means something similar to looping over:
> 
> * each element of `value` if `value` is an array
> * the single item `value` otherwise
> 
> If that is the correct interpretation, wording to this effect would be very helpful. Alternatively, 11.1 might be preceded by language (similar to that used elsewhere in the document) that ensures that `value` is an array before 11.1 is reached.

This would indeed likely make things clearer.

> Beyond the "value of value" wording, 11.1 seems to have an implicit assumption that `value` is either a string, or an array of strings. This is made explicit in 13.4.4 (which may include other expanded `@type` values introduced in the intervening steps) where a `invalid type value` error can be detected. If this restriction was also enforced in 11, it might have the added benefit of adding language that could ensure `value` was an array before 11.1 was reached.

This is indeed the case for values of `@type`, which 11 specifically is describing. We could lift the checking from 13.4.4 into 11.1, but we loose a bit of symmetry with 13.4.3, and there are cases where a type value might be an empty object (which 11.1 should also handle). However, ensuring that the value is always in array form would require altering the input, so I don't think we can do that. But, if we use the "each of its items/elements" it could be inferred that a string has just a single element and an array can have zero or more elements.

> 
> FWIW, the JSON-LD playground seems to suggest that a _third_ possible value for a `@type` key is an empty object:
> 
> > jsonld.SyntaxError: Invalid JSON-LD syntax; "@type" value must a string, an array of strings, or an empty object.

That is implicit in the final sentence "When the frameExpansion flag is set, value may also be an empty dictionary." but only when that frameExpansion flag is set. We could alter the language, but IMO, this handles it.
