### ISSUE TITLE
Expansion test e005 should require `specVersion` to be `json-ld-1.1`

### ISSUE THREAD

**Issue by lo48576** [w3c/json-ld-api#107]
Expansion test `e005` is a test to check the processor returns `invalid remote context` error.
In that test, `specVersion` is not specified, but the input refers itself recursively, so it seems to be `recursive context inclusion` error by JSON-LD 1.0 processor with JSON-LD 1.0 spec.

Input (`e005`):
https://github.com/w3c/json-ld-api/blob/da0dc416c6e5fafd0d9ad583e43e1c6a2f5786b8/tests/expand/e005-in.jsonld#L1-L4

Manifest (`e005`):
https://github.com/w3c/json-ld-api/blob/da0dc416c6e5fafd0d9ad583e43e1c6a2f5786b8/tests/expand-manifest.jsonld#L1074-L1079

`e002` is similar test with `"specVersion": "json-ld-1.0"`.
In this test, processor is expected to abort with `recursive context inclusion` error.

Input (`e002`):
https://github.com/w3c/json-ld-api/blob/da0dc416c6e5fafd0d9ad583e43e1c6a2f5786b8/tests/expand/e002-in.jsonld#L1-L4

Manifest (`e002`):
https://github.com/w3c/json-ld-api/blob/da0dc416c6e5fafd0d9ad583e43e1c6a2f5786b8/tests/expand-manifest.jsonld#L1051-L1057

According to the step 3.2.2 in [JSON-LD 1.0 context processing algorithm](https://www.w3.org/TR/2014/REC-json-ld-api-20140116/#context-processing-algorithm), both `e002` and `e005` should abort with `recursive context inclusion`.
(Note that `invalid remote context` might be returned in the step 3.2.3 in JSON-LD 1.0 spec. The processor won't reach that step with `e005` test case.)

I think the test `e005` should be applied only for processors implemented with JSON-LD 1.1 spec, but not for processors with 1.0 spec.
And if it is correct, `"option": {"specVersion": "json-ld-1.1"}` should be specified in manifest entry for `e005` test.

**Comment by gkellogg** [comment]
Yes, this seems like an overbite and a reasonable change.
