### ISSUE TITLE
Tests page no longer links clearly to tests

### ISSUE THREAD

**Issue by cwebber** [w3c/json-ld-api#113]
A friend and potential implementor sent me a message asking, where are the json-ld tests?  Indeed, I went looking for the old page but couldn't find it.  Instead I found https://w3c.github.io/json-ld-api/tests/ but I couldn't find the actual tests on there anymore.

The answer seems to be https://github.com/w3c/json-ld-api/tree/master/tests so I suggest linking there from that page explicitly.

**Comment by rubensworks** [comment]
They are in fact available on that domain, but it indeed looks like there are no more explicit links to the test manifests.
Here are the actual sources: https://github.com/w3c/json-ld-api/tree/master/tests
For example, the `toRdf` test manifest is available here: https://w3c.github.io/json-ld-api/tests/toRdf-manifest.jsonld

@gkellogg I assume the _Design_ section would be a good place to add explicit links to these manifest URLs?

**Comment by gkellogg** [comment]
I can update the read email to reference manifest.jsonld, which is the starting point for running tests, it references the manifests for each algorithm being tested, which can also be directly linked.
