### ISSUE TITLE
Inconsistency about type maps between API and SYNTAX document.

### ISSUE THREAD

**Issue by pchampin** [w3c/json-ld-api#121]
[Section 9.12 of the syntax doc](https://w3c.github.io/json-ld-syntax/#type-maps) says
>  the values [of a type map] MUST be node objects or strings which expand to node objects.

But [the expansion algorithm](https://w3c.github.io/json-ld-api/#algorithm-2), step 13.8 in particular, do not comply with this definition.

For example, given what the SYNTAX do says, I would expect the following
```
{ "@context": {
    "@version": 1.1,
    "@vocab": "http://example.org/ns/",
    "foo": { "@container": "@type" }
  },
  "foo": {
    "bar": "baz"
} }
```
to expand to
```
[ {
    "http://example.org/ns/foo": [
      {
        "@id": "https://json-ld.org/playground/baz",
        "@type": [ "http://example.org/ns/bar" ]
} ] } ]
```
but instead it expands to
```
[ {
    "http://example.org/ns/foo": [
      {
        "@value": "baz",
        "@type": [ "http://example.org/ns/bar" ]
} ] } ]
```
in both the [playground](http://tinyurl.com/y4t856hk) and the distiller.

I would also expect
```
{ "@context": {
    "@version": 1.1,
    "@vocab": "http://example.org/ns/",
    "foo": {
      "@container": "@type"
    }
  },
  "foo": {
    "bar": { "@value": "baz" }
} }
```
to be rejected. But instead the [playground](http://tinyurl.com/yxfzrfzs) and the distliller both expand it as the previous example.

Note also that the expanded JSON-LD produced in both cases is technically invalid, because the value object's `@type` value can not be an array according to [the data model](https://w3c.github.io/json-ld-syntax/#value-objects).

It can even get worse, generating a value object with *two* types (http://tinyurl.com/yy6x92jk).

I suggest that the expansion algorithm be updated to comply with the syntax document.

**Comment by gkellogg** [comment]
It works properly if you do the following ([playground](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%7B%22%40version%22%3A1.1%2C%22%40vocab%22%3A%22http%3A%2F%2Fexample.org%2Fns%2F%22%2C%22foo%22%3A%7B%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40type%22%7D%7D%2C%22foo%22%3A%7B%22bar%22%3A%22baz%22%7D%7D)):

```json
{ "@context": {
    "@version": 1.1,
    "@vocab": "http://example.org/ns/",
  "foo": { "@type": "@id", "@container": "@type" }
  },
  "foo": {
    "bar": "baz"
  }
}
```

I think we need to add a step before 13.8.3.6.4 or in both 13.8.3.6.4 and 13.8.3.6.5 to verify that _item_ is a node object.

We may need to add something to compaction to be sure it doesn't do the wrong thing, either.
