### ISSUE TITLE
How to handle [Exposed=Windows]

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-api#160]
We can either remove it entirely, but be invalid WebIDL, leave it, with an explanatory note, or invent something else to expose.

Really, this should probably be a TAG issue, as WebIDL should consider non-browser use cases, as it's used extensively elsewhere.

**Comment by dlongley** [comment]
If we are forced to use it, it seems like it should at least be: `[Exposed=(Window,Worker)]` so if a browser ever did implement it, it would be available in workers.

**Comment by gkellogg** [comment]
WG [resolved to close the issue as complete](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-10-18-json-ld#resolution2).
