### ISSUE TITLE
ToRdf can generate invalid quads

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-api#17]
@cwebber originally noticed that it's possible for a JSON-LD document to be composed with `@id` (or other) values that could be used in an attack after serializing to N-Quads.

For example:

```json
{
  "@id": "http://foo/> <http://bar/> <http://baz> .\n<data:little> <data:bobby> <data:tables> .\n<data:in-ur-base",
   "http://killin/#yer": "dudes"
}
```

If this is directly serialized to N-Quads would generate extra statements:

```turtle
<http://foo/> <http://bar/> <http://baz> .
<data:little> <data:bobby> <data:tables> .
<data:in-ur-base> <http://killin/#yer> "dudes" .
```

The same "attack" could be used in property or value positions, including as a datatype IRI or language.

**Comment by gkellogg** [comment]
There are a couple of ways to view this:

1) The ToRdf algorithm is defined to create a dataset, not a serialization, with the dataset composed of quads. In that sense, the statement of the first quad would be `<http://foo/\> \<http://bar/\> \<http://baz\> .\n\<data:little\> \<data:bobby\> \<data:tables> .\n\<data:in-ur-base>`, which is a single IRI, but invalid according to the grammar in RFC3987. It would be the responsibility of either the RDF library, or the N-Quads serializer to properly escape or reject such statements. In this case, we might simply resolve this with a note, and add something to the security section.

2) The algorithm already rejects quads that contain relative IRIs, which are also invalid from the RFC3987 ABNF (they are valid `irelative-part`, not `IRI`). It would be a reasonable tweak to reject any statements which are considered invalid (graph name, subject, predicate, object, datatype or language).

    Step 4.3.1 in the Deserialize JSON-LD to RDF algorithm states, for example:
    > 	If graph name is a relative IRI, continue with the next graph name-graph pair.

    This is repeated on 4.3.1 for subject, 4.3.2.4, and step 1 of the Object to RDF Conversion algorithm. It could instead say “if … is not a valid absolute IRI, continue to the next name-graph pair”, for example. We could also simply update the definition for “absolute IRI” to indicate that it MUST be valid according to the RFC3987 grammar for “IRI" (or the relevant URL document, if we go there).

    There should be a similar check for the IRI in a typed literal, and as Christopher points out, for the language tag. In the case of the language tag, we might just borrow part of the LANGTAG terminal from Turtle:

    > [144s]	LANGTAG	::=	'@' [a-zA-Z]+ ('-' [a-zA-Z0-9]+)*

    excluding the leading ‘@‘, and require that emitted language tags be of this form. We then resolve this by saying that the algorithm **MUST NOT** emit invalid quads, where a valid **RDF triples** or **graph names** where _valid_ is defined as having an **IRI** or **blank node identifier** in proper lexical form. The definition of **language-tagged string** already requires the **language tag** be well-formed according to BCP47.

**Comment by gkellogg** [comment]
The gist of side conversations on this is that it is best to require the algorithm to emit only valid quads, meaning that all IRIs are valid absolute IRIs, and language tags conform to BCP47, as is already described in the definition of **language-tagged string**.

Language will be added that requires this in general, and for specific processing steps and tests will be added to validate this. This will allow us to remove specific language on relative IRIs being dropped.

**Comment by davidlehn** [comment]
I missed the chance to review #18 before it was merged and this issue closed.  I've been looking at js/py implementation details and I think this may need some further consideration.  I've also looked at https://github.com/ruby-rdf/json-ld/commit/b3e943d92624f405d96c468c14ec2376366da0a7.

- Why does the toRdf algorithm drop bad data instead of causing an error?  What is the use case where you would want toRdf to silently ignore bad data?  The tests enforce this using "positive" tests with empty outputs.

- It seems odd not to have the same restrictions for every algorithm that the data be well formed.  Could the data validity restrictions and/or checks happen elsewhere?  Why are they only happening in toRdf?

- As an implementation performance consideration, these checks should be optional somehow.  If you already know your input data is well formed, there's no reason to take a hit on checking it again.  How should the APIs be designed for this?

**Comment by gkellogg** [comment]
> Why does the toRdf algorithm drop bad data instead of causing an error? What is the use case where you would want toRdf to silently ignore bad data? The tests enforce this using "positive" tests with empty outputs.

The consensus from discussion was to drop non-conforming issues. Of course, an implementation could always choose to raise an error using applications-specific flags. The algorithm previously dropped relative IRIs, rather than raised an error, which is consistent with this behavior. Of course, the WG could consider revisiting this, or having a separate check to see if IRIs or language tags are specifically invalid, rather than simply incomplete, and cause an error to be raised, but this might need to happen in expansion, instead of toRdf.

> It seems odd not to have the same restrictions for every algorithm that the data be well formed. Could the data validity restrictions and/or checks happen elsewhere? Why are they only happening in toRdf?

The algorithm previously did this for a class of invalid terms, notably relative IRIs. IIRC, there was some discussion of making a more general check in expansion and raising an error, but that didn't get uptake.

> As an implementation performance consideration, these checks should be optional somehow. If you already know your input data is well formed, there's no reason to take a hit on checking it again. How should the APIs be designed for this?

That argument could be made about anyplace algorithms check for unexpected data, yet we do have such checks. An argument for doing this in expansion is that some implementations allow you to invoke an algorithm, such as toRdf, using explicitly pre-expanded data, which might avoid these checks, but that would still leave the checks for relative IRIs. Really, the code just replaces that for checking relative IRIs, adds a check for datatype IRIs which should have always been there, and adds a check for language-tags, so no real impact on performance vis-a-vis the previous algorithm.

Feel free to re-open the issue and mark "needs discussion" to get a discussion planned for a telecon.
