### ISSUE TITLE
Clarify trailing text in expansion algorithm

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#175]
The [expansion algorithm](https://w3c.github.io/json-ld-api/#expansion-algorithm) includes this trailing text:

> If, after the above algorithm is run, the result is a map that contains only an @graph entry, set the result to the value of @graph's value. Otherwise, if the result is null, set it to an empty array. Finally, if the result is not an array, then set the result to an array containing only the result.

It is not clear to me if this post-handling of the result is applied universally to all values returned out of the expansion algorithm. For example, step 1 ends `return null`. Why use `null` here instead of an empty array if the post-processing will always do the conversion?

Alternatively, based on the overview in 5.1.1, I think it's possible that the post-processing detailed in the trailing text is meant to apply only to steps 6 and beyond. If that's the case, the language "after the above *algorithm* is run" (emphasis added) is misleading.

The use of `return` throughout the algorithm which is then required to have post-processing applied to it is confusing and a strange overload to what I would think of as the normal definition of `return`. Can this please be clarified and the language improved to avoid the confusion as to what parts of the algorithm the post-processing is applied to, and to remove any unnecessary values (such as the `null` return in step 1) which are almost immediately replaced with other values?

**Comment by gkellogg** [comment]
Good points. Also, it's intended that the content of `@graph` be used in place of the `@graph` entry, only when `@graph` contains an object (probably can't), or an array containing a single object.

**Comment by gkellogg** [comment]
There are other cases where we've favored using _otherwise_ (or similar) to avoid returns within the code. We might say "skip the following steps", instead, which makes it clear that the algorithm includes the "if, after the above algorithm is run, ..." bit. And then make sure that the post-processing steps considers the different forms of _result_.
