### ISSUE TITLE
Clarify use of base IRI in IRI expansion algorithm

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#180]
[IRI expansion algorithm](https://w3c.github.io/json-ld-api/#algorithm-4) is described as taking an optional argument "document relative" that specifies:

> whether value can be interpreted as a relative IRI against the **document's** base IRI

(emphasis added)

However, step 8 says:

> Otherwise, if document relative is true set value to the result of resolving value against the base IRI.

I believe this is actually meant to resolve using the base IRI from active context (see, for example, test t0062), but the only related language (above) indicates that it is the base IRI of the document. Please clarify this.

**Comment by gkellogg** [comment]
Yes, it should explicitly say base IRI from active context.

I had a thought that we could create a lexicon of shortcuts to common phrases, such as this, to simplify the language, but it’s a little late in the process.
