### ISSUE TITLE
Clarify text regarding container mappings in algorithms

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#181]
In the [Create Term Definitiion](https://w3c.github.io/json-ld-api/#algorithm-0) algorithm, step 22 deals with an entry's '@container' value. In 22.1:

> Initialize container to the value associated with the @container entry, which MUST be either @graph, @id, @index, @language, @list, @set, @type, or an array containing exactly any one of those keywords, an array containing @graph and either @id or @index optionally including @set, or an array containing a combination of @set and any of @index, @id, @type, @language in any order .

(Note that this definition allows both scalar and array types.)

However, subsequent steps talk about a container mapping as though the type were known to be an array:

* In 22.4: "If container mapping is @type" (which might imply that it can't be an array containing '@type'(?))
* In 23.1: "or container mapping does not include @index" (implying that it must be an array?)

And in the [expansion algorithm](https://w3c.github.io/json-ld-api/#algorithm-3):

* In 5.2.2: "If the container mapping of active property includes @list" (implying that it can't *be* '@list'?)
* In 13.7: "Otherwise, if container mapping includes @language" (implying that it can't *be* '@language'?)
* In 13.8: "Otherwise, if container mapping includes @index, @type, or @id"
* And again in 13.8.3.1, 13.8.3.2, 13.8.3.7.1, 13.8.3.7.2, 13.8.3.7.3, , 13.8.3.7.4, 13.8.3.7.5, 13.11 and 13.12

As an aside, the text of 22.4 should probably clarify "container mapping" as "the [container mapping] of definition".

**Comment by gkellogg** [comment]
Even though `@container` can be a scalar, I try to consistently use the "if the container mapping of active property includes `@list`", and so forth. We need to make a pass to ensure consistency. Would you say that "@list" includes "@list"?

We could also clarify when creating a term expansion that the value of `@container` is coerced to an array.

**Comment by kasei** [comment]
I wouldn't assume that `includes` language would mean `A includes A`, no. However, if the spec was very clear about making that explicit (e.g. that `includes` implies that the left-hand side is either a scalar or an array, and is either equal to or contains the right-hand side), I'd be OK with that language being used throughout.

I'd prefer text about coercion to arrays, though.

**Comment by gkellogg** [comment]
If we simply coerce scalar values to arrays when creating term definitions, then the expansion/compaction and other algorithms can use _includes_ when inspecting that term definition. This could change 22.3 and 22.4 as follows:

> 22.3 Set the container mapping of definition to container, **coercing to an array, if necessary**.
> 22.4 If container mapping **includes** `@type`:
