### ISSUE TITLE
Remove redundant conditional statements in expansion algorithm step 13.11

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#185]
The [expansion algorithm](https://w3c.github.io/json-ld-api/#algorithm-3) step 13.11 says:

> If container mapping includes @list and expanded value is not already a list object, convert expanded value to a list object by first setting it to an array containing only expanded value if it is not already an array, and then by setting it to a map containing the key-value pair @list-expanded value.

This sentence seems to have redundant conditional statements regarding `expanded value` not being a list/array. Assuming "list" and "array" are used interchangeably, it seems the second conditional statement "if it is not already an array" can be removed.

**Comment by pchampin** [comment]
> Assuming "list" and "array" are used interchangeably

That's a wrong assumption. Notice that the text says "list object", which is a JSON-LD specific term (with a link to its definition, btw), which reads:

> A list object is a map that has a `@list` key. It may also have an `@index` key, but no other entries.

**Comment by kasei** [comment]
My mistake. Thanks.
