### ISSUE TITLE
Markup regarding local contexts in Create Term Definition is confusing

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#193]
The [Create Term Definition algorithm](https://w3c.github.io/json-ld-api/#algorithm-0), step 23.2 says:

> Initialize context to the value associated with the @context entry, which is treated as a local context.

Here, `local context` has markup that indicates it as a variable, though it is not a variable.

Further on, step 23.4 says:

> Set the local context of definition to context.

Again, `local context` is indicated as a variable. I believe the intention here is to set the `@context` property of `definition` to the variable `context`, but the wording and markup here confounds this reading.

**Comment by gkellogg** [comment]
Variables in ReSpec are scoped to the algorithm they're used in, but call sequences _should_ use the variable notation when saying that some value is used for a parameter (e.g., _active context_ for _local context_). Even though that _local context_ would nominally be scoped in the algorithm that it's described in, it seems the only reasonable way to indicate a parameter assignment.

We're not consistent on this, so I'll make a pass through to try to achieve such consistency.

In the case of "Set the _local context_ of _definition_ to _context_", it seems more appropriate to use a reference to the definition for "local context", as the data-structure for [term definition](https://www.w3.org/TR/json-ld11/#dfn-term-definition) doesn't have variables, but defined entries.
