### ISSUE TITLE
Missing text in expansion algorithm

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#213]
The [Expansion algorithm](https://w3c.github.io/json-ld-api/#algorithm-3) step 13.4.3 seems to be missing text:

> If result already has an expanded property entry, for @included or @type.

**Comment by gkellogg** [comment]
Looks like that came from https://github.com/w3c/json-ld-api/commit/d930363bc3dcac1fcc4d128dd46d0aa2473c336e#diff-eacf331f0ffc35d4b482f1d15a887d3bR2384, and was an added in error, but it's meaningless.
