### ISSUE TITLE
Clarify text in Expansion Algorithm step 12 regarding variable initialization

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#215]
[5.1.2 Expansion Algorithm](https://w3c.github.io/json-ld-api/#algorithm-3) step 12 says:

> Initialize two empty maps, `result` and `nests`. Initialize `input type` to the last value of the first entry in `element` expanding to `@type`, ordering entries lexicographically by key.

Should the text regarding `input type` include what to do if no such value exists (e.g. if no entries in `element` expand to `@type`)?

**Comment by gkellogg** [comment]
I'll add "(if any)".

**Comment by gkellogg** [comment]
The implication is that if it doesn't exist, it is `null`/undefined. I think this would be a common interpretation.
