### ISSUE TITLE
Unused variable defined for property-scoped contexts in expansion algorithm

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#216]
[5.1.2 Expansion Algorithm](https://w3c.github.io/json-ld-api/#algorithm-3) steps 3 says:

> If `active property` has a term definition in `active context` with a local context, initialize `property scoped context` to that local context.

However, this seems to be the only occurrence of `property scoped context` in the entire document. It seems that there's a missing hyphen in the variable name, as `property-scoped context` does appear later in the algorithm.

**Comment by gkellogg** [comment]
See comment in #214, it should have been "property-scoped context".

Dupilcate of #214.
