### ISSUE TITLE
Unclear IRI Expansion of blank-node-mapped prefixes

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#219]
The [test t0038](https://github.com/w3c/json-ld-api/blob/master/tests/expand/0038-in.jsonld#L31) indicates that expanding a compact IRI such as `term:AppendedToBlankNode` where the prefix has an IRI mapping to a blank node ID `_:term` should result in the concatenated blank node ID `_:termAppendedToBlankNode`. I do not believe the spec supports this expansion.

[IRI Expansion](https://w3c.github.io/json-ld-api/#algorithm-4) step 6.4 seems to be the most relevant part of the spec:

> If `active context` contains a term definition for `prefix` having a non-null IRI mapping and the `prefix flag` of the term definition is `true`, return the result of concatenating the IRI mapping associated with `prefix` and `suffix`.

However, I do not believe this applies, as I believe the `prefix flag` value for the term definition will be false. The [Create Term Definition algorithm](https://w3c.github.io/json-ld-api/#algorithm-0) step 16.6 is where `prefix flag` would be set:

> If `term` contains neither a colon (:) nor a slash (/), `simple term` is true, and if the IRI mapping of `definition` ends with a URI gen-delim character, set the `prefix flag` in definition to `true`.

In this case, the IRI mapping (`_:term`) does not end with a gen-delim character (`":" / "/" / "?" / "#" / "[" / "]" / "@"`), and so `prefix flag` is not set.

Have I missed some other relevant part of the spec here? @gkellogg mentioned to me on IRC that this is a holdover from JSON-LD 1.0 that must be preserved. Given that, do the details in IRI Expansion and Create Term Definition need to be updated to properly support this feature?

**Comment by gkellogg** [comment]
* Step 8 of Create Term Definition ends with " Set _simple term_ to `true`."
* Step 16.6 says "If term contains neither a colon (:) nor a slash (/), _simple term_ is `true`, and if the IRI mapping of definition ends with a URI gen-delim character, set the _prefix flag_ in definition to `true`."

The point that may need to be clarified is the gen-delim bit, which it does not have, but this is really only pertinent for an IRI. So, it should probably say "... gen-delim character, **or the IRI mapping is a blank node label**, ..."

Ideally, we wouldn't need to do this, and the WG may consider that it is not important to preserve the ability to append strings to blank node terms. This was true for 1.0, and there is a test for this, but it's questionably that any existing code actually depends on this, and IMHO, it is an archaic mechanism that is wrong-headed.

**Comment by pchampin** [comment]
If I understand correctly, this is a very similar issue to #205 . The decision there was to mark the test as 1.0 only. Probably we should do the same for [test t0038](https://github.com/w3c/json-ld-api/blob/master/tests/expand/0038-in.jsonld#L31)?

**Comment by gkellogg** [comment]
Yes, it’s a duplicate if #205, but there’s still a wording problem. Worth a revisit. If we make it 1.0 only, we should make it that such a term is not a simple term. Otherwise, update wording so gen-delim is not considered for bnodes

**Comment by gkellogg** [comment]
Closing as duplicate
