### ISSUE TITLE
Meaning of tests with only specVersion

### ISSUE THREAD

**Issue by rubensworks** [w3c/json-ld-api#227]
The following toRdf tests set `"specVersion"` to `"json-ld-1.0"` without setting `"processingMode"` to `"json-ld-1.0"`:

* t0118
* te014
* te026
* te038
* te071
* te115
* te116

I assume this means that these should *only* be tested by JSON-LD 1.0 processors that *don't* implement 1.1. Is this correct?

In any case, I'm wondering if it makes sense to change these tests to also set `"processingMode"` to `"json-ld-1.0"` so that they can still be tested by any newer processors that want to fully support 1.0 as well.

**Comment by gkellogg** [comment]
processingMode json-ld-1.0 is how a 1.1 processor should behave in 1.0 mode. It is subtly different from specVersion json-ld-1.0. 

A 1.1 processor shouldn’t run 1.0 tests, and (at least theoretically) a 1.0 processor should _only run 1.0 tests.

**Comment by rubensworks** [comment]
So this means that a 1.1 processor is not (at the same time) a 1.0 processor?

Considering the backwards-compatibility of 1.1-1.0, it feels a bit unintuitive to me that a 1.1 processor should not run 1.0 tests.

Was there a particular reason why this distinction between processingMode and specVersion was made?

**Comment by gkellogg** [comment]
There are some minor areas I which we’ve diverged, consistent with our charter. Largely in areas covered by errata.

**Comment by azaroth42** [comment]
No issue, closing.
