### ISSUE TITLE
remove requirement on blank node naming

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-api#25]
Currently, the algorithms are quite proscriptive on how blank node identifiers are named, principally to make it easier to test the results, however for some things this becomes difficult or impossible, and inhibits algorithms from being conformant based on a strict textual/structural validation of the results.

Making the test suite easy to run is important to get implementation compliance, however.

* Compact and Expand tests don't mess with blank node identifiers, so they should not be a problem.
* Flattening and Framing do create specific blank node identifiers, but could be tested using a bijective comparison, as suggested in the [README](https://github.com/w3c/json-ld-api/blob/master/tests/README.md)
* ToRdf generates a dataset, and normal RDF Isomorphism or normalization can be used. Previously, the quads were ordered, and a textual comparison can be made. This could still be supported for implementations that stick to the blank node naming schema.
* FromRdf can be problematic if the input quads are not ordered, as arrays containing multiple values may have random order. The bijective comparison discussed for Flattening may be likely, or the test inputs can be massaged so that a strict input ordering can be assured.

Currently the [Generate Blank Node Identifier](https://w3c.github.io/json-ld-api/#generate-blank-node-identifier) algorithm is normative, and is called out in some places for the predictable way in which blank nodes are nomad. The proposal is to make this non-normative, and update sections that use it to be less proscriptive on how blank node identifiers are named. The test README can be updated to suggest using this to make comparing test results simpler, or to use the bijective approach suggested in the README. This requires more elaboration, but is essentially something like the following:

1. Generate RDF datasets from the expected JSON output and the actual JSON output using the [Deserialize JSON-LD to RDF algorithm](https://w3c.github.io/json-ld-api/#deserialize-json-ld-to-rdf-algorithm).
2. Create a bijective mapping for blank nodes in the result dataset to the expected dataset as described in [RDF11-Concepts](https://www.w3.org/TR/rdf11-concepts/#section-dataset-isomorphism).
3. Using the resulting mapping, replace the blank node identifiers in the result JSON.
4. Reorder array contents for those arrays which do not map to a `@list` container based on the lexical value of strings, or the lexical value of their `@id` or `@value` members.
5. Compare the resulting JSON using a standard structural comparison.

Another alternative would be to create a service to perform such a comparison, but IMHO, developers likely to use an algorithm that does not simply use sorted input and standardized blank node identifier generation are probably capable of such a comparison.

**Comment by azaroth42** [comment]
PROPOSAL:  Accept above :)

**Comment by azaroth42** [comment]
[WG Resolution](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-09-21-json-ld#resolution3) on call of 2018-09-21 was to mark the normative blank node naming algorithm at risk in next WD, and have a blog post about this issue and the obsoleting of the blank node as property feature; if no feedback is received than we can proceed in the subsequent WD

**Comment by azaroth42** [comment]
Marking this editorial, as the next time we need to consider it is after the 2nd PWD.
