### ISSUE TITLE
Issue with Expansion handling of type maps and @none

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#264]
[Expansion algorithm](https://w3c.github.io/json-ld-api/#expansion-algorithm) step 13.8.3.7.5:

> Otherwise, if `container mapping` includes `@type` initialize `types` to the concatenation of `expanded index` with any existing values of `@type` in `item`. If `expanded index` is `@none`, do not concatenate `expanded index` to `types`. Add the key-value pair (`@type-types`) to `item`.

Based on test tm012, I don't think this key-value pair is meant to be added to `item` in the case that `expanded index` is `@none`. If that is the case, this text can likely be simplified, as the "If `expanded index` is `@none`" condition will apply to the entire body of this step.

Also, the word choice of "concatenation" is confusing here. By context, I believe that what is being described is an *array*, `types`, that should possibly contain `expanded index`, and definitely contain any existing values of `@type` in `item`. Is there a way to improve this language to not risk confusion with string concatenation?

**Comment by gkellogg** [comment]
It probably should have used wording symmetric to the previous, where a check for _expanded index_ being `@none` predicates the further steps.

The following should have the intended meaning:

> Otherwise, if _container mapping_ includes `@type` and _expanded index_ is not `@none`, initialize _types_ to the a new array consisting of _expanded index_ followed by any existing valuers of `@type` in _item_. Add the key-value pair (`@type`-types) to _item_.

Note that we also use "concatenation" in 13.8.3.7.2 (for `@index`), but I believe that [concatenation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat) is a well defined concept on arrays, so rewording simply to replace this would be gratuitous.

**Comment by kasei** [comment]
@gkellogg I think concatenation is well-defined when both operands are arrays. But in this case, it's an array and a string, right? (Which in the JS case would be `push`, but might also be called `append`...)

**Comment by kasei** [comment]
Agree with your new proposed text; it is much clearer.

**Comment by gkellogg** [comment]
@kasei this is updated in PR #274. Please indicate if this satisfies your issue.

**Comment by kasei** [comment]
@gkellogg yes, looks good. Thanks.
