### ISSUE TITLE
toRdf and fromRdf algorithms need WebIDL API methods defined

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-api#27]

**Comment by azaroth42** [comment]
Is this editorial, or does it need discussion?

**Comment by gkellogg** [comment]
Editorial, but we may discuss things in the PR review.

**Comment by BigBlueHat** [comment]
Mostly as an aside: the [RDF.js CG](https://www.w3.org/community/rdfjs/) is bringing in lots of code and working it toward conformance with the [Interface Specification: RDF Representation](http://rdf.js.org/). There's no existing conflict (that I've seen) between this WebIDL and their JS API, but it might serve both communities well if we keep each other appraised of any overlap (if/when it occurs).

Thanks for your work on this, @gkellogg!

**Comment by gkellogg** [comment]
@BigBlueHat thanks for the reference, I was aware of this, but had forgotten the details.

Technically, we should probably be using interfaces like [RDF source](https://www.w3.org/TR/rdf11-concepts/#dfn-rdf-source), which the RDF Representation describes using the `Source` interface.

The `Stream` interface would seem to be better modeled using the WebIDL `iterable` construct, which is the primary thing we depend on for Convert to JSON-LD from RDF.

Interestingly, they don't really have the equivalent of an `add` method, which might be done in `Sink`, or through assigning to `Quad.graph`. However, they could consider adding it to the `Sink` interface.

But, the RDF Representation spec, I think, is more designed to describe actual JavaScript implementations, rather than an abstract model for dealing with RDF concepts.

**Comment by BigBlueHat** [comment]
> But, the RDF Representation spec, I think, is more designed to describe actual JavaScript implementations, rather than an abstract model for dealing with RDF concepts.

Quite likely. The spec itself has also set dormant for quite awhile. I believe folks in the CG are hoping to revisit that work once they've consolidated some of the implementing code projects into the [CG's org](https://github.com/rdfjs). But given that it will only ever (by design) be JS-centric, you're probably quite right. Something to keep an eye on (and people to work with), but probably not a reason to change course per se.
