### ISSUE TITLE
Extraneous step in Deserialize JSON-LD to RDF Algorithm?

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#278]
[Deserialize JSON-LD to RDF Algorithm](https://w3c.github.io/json-ld-api/#algorithm-12) step 1.3.2.5.1 says:

> item is a value object, list object, or a node object.

Is this meant to be validation that might raise an error condition? If not, would it be better included as a note, not its own step?

**Comment by gkellogg** [comment]
No, not a validation step, an assertion of truth. It could be a note at the beginning of 1.3.2.5.2, instead.

**Comment by gkellogg** [comment]
@kasei see update in PR #286. Please indicate if this addresses the issue.

**Comment by kasei** [comment]
@gkellogg looks good, thanks!
