### ISSUE TITLE
Mixed use of "append" and "add" in reference to an RdfGraph in Deserialize JSON-LD to RDF Algorithm

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#279]
[Deserialize JSON-LD to RDF Algorithm](https://w3c.github.io/json-ld-api/#algorithm-12) step 1.3.2.5.3 says:

> Append a triple composed of `subject`, `property`, and the result of using the Object to RDF Conversion algorithm passing `item` and `list triples` to `triples`, unless the result is `null`, indicating a non-well-formed resource that has to be ignored.

The use of "append" language in reference to `triples` is confusing here, as `triples` is an `RdfGraph` which can have triples added to it with the `add` method (which is what step 1.3.2.5.4 does).

**Comment by gkellogg** [comment]
@kasei see update in PR #286. Please indicate if this addresses the issue.

**Comment by kasei** [comment]
@gkellogg 1.3.2.5.2 now includes an extra "using its":

> to triples using its using its add method

Other than that, yes, this looks good. Thanks.
