### ISSUE TITLE
Accidental variable override in Deserialize JSON-LD to RDF Algorithm 1.2

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#281]
[Deserialize JSON-LD to RDF Algorithm](https://w3c.github.io/json-ld-api/#algorithm-12) step 1.2 says:

> Otherwise, initialize `graph` as an empty `RdfGraph` and add to `dataset` using its `add` method along with `graph name` for `graphName`.

The initialization of the `graph` variable here seems to conflict with the initialization in the enclosing loop of step 1, and its subsequent use in step 1.3.

**Comment by gkellogg** [comment]
@kasei see update in PR #286. Please indicate if this addresses the issue.

**Comment by kasei** [comment]
@gkellogg looks good, thanks!
