### ISSUE TITLE
Issue with dropping @language-only objects during expansion

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#284]
Test [t0008](https://w3c.github.io/json-ld-api/tests/expand-manifest.html#t0008) expands:

```json
{
  "@context": {
    "ex": "http://example.org/vocab#"
  },
  "@id": "http://example.org/test",
  "ex:test": { "@value": "test",  "@language": "en" },
  "ex:drop-lang-only": { "@language": "en" },
  "ex:keep-full-value": { "@value": "only value" }
}
```
to:

```json
[
  {
    "@id": "http://example.org/test",
    "http://example.org/vocab#test": [ { "@value": "test", "@language": "en" } ],
    "http://example.org/vocab#keep-full-value": [ {"@value": "only value"} ]
  }
]
```

Based on the current text of [expansion algorithm](https://w3c.github.io/json-ld-api/#expansion-algorithm) steps 18 and 21, `ex:drop-lang-only` should not be dropped. (Expansion 13.9 will recursively call expansion on `"ex:drop-lang-only": { "@language": "en" },` and steps 18 and 21 will result in an empty array being returned.)

After a discussion with @gkellogg on irc, I believe the fix to this is to update step 18 from:

> If `result` is a map that contains only the entry `@language`, set `result` to `null`.

to:

> If `result` is a map that contains only the entry `@language`, return `null`.

**Comment by gkellogg** [comment]
@kasei changes in PR #287. Let us know if you're satisfied.

**Comment by kasei** [comment]
@gkellogg looks good, thanks!
