### ISSUE TITLE
Wrong variable use in Expansion handling of @index maps

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#290]
[Expansion algorithm](https://w3c.github.io/json-ld-api/#expansion-algorithm) step 13.8.3.7.2 says:

> If `container mapping` includes `@index`, `index key` is not `@index`, `item` does not have an entry `@index` and `expanded index` is not `@none`, initialize `index property values` to the concatenation of `expanded index` with any existing values of `index key` in `item`. Add the key-value pair (`expanded index`-`index property values`) to `item`. If `item` is a value object, it MUST NOT contain any extra properties; an `invalid value object error` has been detected and processing is aborted.

Based on test [tpi06](https://w3c.github.io/json-ld-api/tests/expand-manifest.html#tpi06), I don't believe the variables used here are correct. To get the expected output from tpi06, I think the text should read (in part):

> If `container mapping` includes `@index`, `index key` is not `@index`, `item` does not have an entry `@index` and `expanded index` is not `@none`, initialize `index property values` to the concatenation of the value expansion of `index` (passing `index key` as `active property`) with any existing values of `expanded index key` in `item`. Add the key-value pair (`expanded index key`-`index property values`) to `item`.

This also requires defining `expanded index key` as the IRI Expansion of `index key`.

**Comment by gkellogg** [comment]
Need to use similar wording for expand value elsewhere. "If the _expanded index_ is not `@none`, then set the _expanded index_ to the result of the Value Expansion algorithm, passing the _active context_, _index key_, and _index_ as _value_."

**Comment by gkellogg** [comment]
@kasei Updated text in #291. There was another issue where _index key_ wasn't used properly.

Please acknowledge.

**Comment by kasei** [comment]
@gkellogg looks good, thanks!
