### ISSUE TITLE
Issue with expansion of null @value values.

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#292]
Expand test [t0019](https://w3c.github.io/json-ld-api/tests/expand-manifest.html#t0019) seems to reveal an issue with the [Expansion algorithm](https://w3c.github.io/json-ld-api/#expansion-algorithm) step 15.2:

> If the value of result's @value entry is null, then set result to null.

I believe this needs to *return* `null` instead of just updating the value of `result`. This will prevent that null from being converted to an empty array in step 21.

**Comment by gkellogg** [comment]
@kasei good catch, moved it below the check for `@json`, and also check for empty array.

Please acknowledge.

**Comment by kasei** [comment]
@gkellogg looks good, thanks!
