### ISSUE TITLE
Possible issue with Expansion handling of @reverse

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#294]
Based on [test t0066](https://w3c.github.io/json-ld-api/tests/expand-manifest.html#t0066), I think there is a problem with the handling of `@reverse` data in [Expansion](https://w3c.github.io/json-ld-api/#expansion-algorithm) steps 13.4.13.3 and 13.4.13.4.

13.4.13.2 sets the value of `expanded value` to the result of a recursive call to the Expansion algorithm, and then 13.4.13.3 and 13.4.13.4 both test `expanded value` as if it were a map. However, I think based on the current text of the expansion algorithm, `expanded value` will always be an array at this point. Is it possible 13.4.13.3 and 13.4.13.4 need to loop over all values returned from the recursive call instead of operating directly on `expanded value`?

**Comment by gkellogg** [comment]
Looks like we changed the wording in PR #175 to always return an array, where before, it would return an object; I don't recall now why we did this.

But, 13.4.13.2 needs to be updated, and perhaps others; I'll have a look around.

**Comment by gkellogg** [comment]
This also goes back to changes in #175. I think the change to always return an array came about because there is text at the end of the 1.0 algorithm, which is missing:

If, after the above algorithm is run, the result is a JSON object that contains only an @graph key, set the result to the value of @graph's value. Otherwise, if the result is null, set it to an empty array. Finally, if the result is not an array, then set the result to an array containing only the result.
This paragraph, which is run after the algorithm, so is not part of the recursive algorithm, got rolled into steps 20-22. We should probably revert the change from #175 which moved these up, and go back to the 1.0 description, so that when the expansion algorithm is passed an object, it typically returns an object, and not an array. We can re-examine some of the other changes that came as a consequence of this.

**Comment by gkellogg** [comment]
From #175:

> It is not clear to me if this post-handling of the result is applied universally to all values returned out of the expansion algorithm. For example, step 1 ends return null. Why use null here instead of an empty array if the post-processing will always do the conversion?

I think what was unclear here is that this paragraph only applied to the end of the outermost layer of processing, where we are returning a normalized form (without sole outer `@graph` and as an array). Perhaps changing the text to say "After the above algorithm is run at the outermost level, perform the following steps before final completion of the algorithm:"

**Comment by kasei** [comment]
I opened #175 because having algorithm step-like rules included in prose and not in numbered steps was confusing. I think the need for language like "the outermost level" already hints at the fact that such prose is trying to make up for the fact that what is being described is really two different algorithms. If it's not possible to describe it explicitly as two separate algorithms, I much prefer the current approach of having everything be a part of the numbered steps, but it's clear that the specifics of the current text might still need some work.

**Comment by kasei** [comment]
(After reading your comments on [my gist](https://gist.github.com/kasei/d4d6cecfeafcf6299bc145039b382123), here's a fuller response:)

FWIW, I would strongly prefer not reverting to the 1.0 language without updates to the language used at most of the places where the expansion algorithm is called. Ideally I think this would be better resolved by breaking up Expansion into multiple sub-algorithms:

* the main body of the current expansion algorithm
* steps 13 and 14 which currently require the use of the "recursively repeat" language (which differs from all other uses of "recursive" invocation in the spec)
* the 1.0-era post-processing text, but described using algorithmic steps, not prose

I understand CR makes this sort of change difficult, but I think it would result in a much simpler description of the expansion algorithm.

**Comment by gkellogg** [comment]
@kasei this should resolve this particular issue, and some related issues where the result of the expansion algorithm was expected to be a map, not an array, which was inadvertently introduced in PR #184.

Please acknowledge if this satisfies the issue.

**Comment by kasei** [comment]
@gkellogg FYI, #299 fixed 4 tests for me, but caused regression in 11 others. I'll look into them and see what's going on.

**Comment by kasei** [comment]
@gkellogg first issue I see is with the new `expand` JsonLdProcessor text step 7.1:

> If expanded output is a map that contains only an @graph entry, set expanded output that value.

By moving this out of the main [Expansion](https://w3c.github.io/json-ld-api/#expansion-algorithm) algorithm, I think test [t0084](https://w3c.github.io/json-ld-api/tests/expand-manifest.html#t0084) ends up with a double `@graph`.

**Comment by gkellogg** [comment]
I think step 13.8.3.7.1 should say:

> If _container mapping_ includes `@graph`, **and _item_ is not a _graph object_**, set item to a new map containing the key-value pair @graph-item, ensuring that the value is represented using an array.

**Comment by kasei** [comment]
That improves the situation, but I think the following text about ensuring `index` is an array is still required.

**Comment by gkellogg** [comment]
Can you point out in the updated PR, where text is missing?

**Comment by kasei** [comment]
Oh, actually, I think this might instead be about the JsonLdProcessor expand step 7.3. By pulling that out of the [Expansion](https://w3c.github.io/json-ld-api/#expansion-algorithm) algorithm, [t0084](https://w3c.github.io/json-ld-api/tests/expand-manifest.html#t0084) ends up with `"@graph": {...}` instead of `"@graph": [{...}]`.

**Comment by gkellogg** [comment]
Expected result is the following:

```json
[{
  "http://example.org/input": [{
    "@index": "g1",
    "@graph": [{
      "http://example.org/value": [{"@value": "x"}]
    }]
  }]
}]
```

This would come from step 13.8.3.7.1 saying "ensuring that the value is represented using an array".

**Comment by kasei** [comment]
@gkellogg I'm now confused. The suggested text change to 13.8.3.7.1 will result in that step **not** being processed in this case, because `item` **is** a graph object. So we're left with an `item` that is a map, that I think results in output containing `"@graph": {...}` (without an array).

**Comment by kasei** [comment]
I *think* this might be solved by adding a new step 13.8.3.7.1a (between .1 and .2):

> Otherwise, if `item` is a graph object and the value of `@graph` in `item` is not an array, set it to a new array containing only that value.

(or words to that effect)

**Comment by gkellogg** [comment]
It should already be in an array form because of 13.4.5:

> If _expanded property_ is `@graph`, set _expanded value_ to the result of using this algorithm recursively passing _active context_, `@graph` for _active property_, _value_ for _element_, and the `frameExpansion` and `ordered` flags, **ensuring that _expanded value_ is an array of one or more maps**.

**Comment by kasei** [comment]
Yes, you're right. I had a bug in 13.4.5.

**Comment by kasei** [comment]
@gkellogg I'm happy with #299, thanks.
