### ISSUE TITLE
Issue in Object to RDF Conversion handling of @json typed values

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#298]
[Object to RDF Conversion](https://w3c.github.io/json-ld-api/#object-to-rdf-conversion) step 6 says:

> If `datatype` is not `null` and not a well-formed IRI, return `null`.

However, step 8 begins:

> If `datatype` is `@json`...

`@json` does not match "the ABNF for IRI as described in [RFC3987]", and so is not a well formed IRI. Step 6 should return `null`, but step 8 is clearly meant to handle these typed values.

**Comment by gkellogg** [comment]
@kasei see if that language is clear.

**Comment by kasei** [comment]
@gkellogg looks good, thanks!
