### ISSUE TITLE
Option to compact terms but not values

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-api#3]
**_This was raised by [Fabian Steeg](http://lists.w3.org/Archives/Public/public-linked-json/2014Mar/0033.html):**_

> The JSON-LD API document states: "Expansion has two important goals: removing any contextual information from the document, and ensuring all values are represented in a regular form."
> 
> Is there a way to achieve only the second goal, the regular form, but with compact terms? Using compaction with compactArrays=false is pretty close, but there is still at least one thing that is irregular and causing issues for me.
> 
> Given this input:
> 
> ```
> {
>   "http://example.com/foo": "foo-value",
>   "http://example.com/bar": {
>     "@value": "bar-value",
>     "@language": "en"
>   },
>   "@context": {
>     "foo": "http://example.com/foo",
>     "bar": "http://example.com/bar"
>   }
> }
> ```
> 
> I get this from compaction with compactArrays=false:
> 
> ```
> {
>   "@graph": [{
>     "foo": ["foo-value"],              <-- foo: array of strings
>     "bar": [{                          <-- bar: array of objects
>       "@language": "en",
>       "@value": "bar-value"
>     }]
>   }],
>   "@context": {
>     "foo": "http://example.com/foo",
>     "bar": "http://example.com/bar"
>   }
> }
> ```
> 
> But I'd like to get this (which is what expansion does to the values):
> 
> ```
> {
>   "@graph": [{
>     "foo": [{                          <-- both foo and bar:
>       "@value" : "foo-value"               array of objects
>     }],
>     "bar": [{
>       "@language": "en",
>       "@value": "bar-value"
>     }]
>   }],
>   "@context": {
>     "foo": "http://example.com/foo",
>     "bar": "http://example.com/bar"
>   }
> }
> ```
> 
> So I guess I'm looking for something like a compactValues=false option.
> 
> Is there some way to get this output?

Original issue [Option to compact terms but not values #338](https://github.com/json-ld/json-ld.org/issues/338).

**Comment by azaroth42** [comment]
Seems similar to the `@type` as `@container:@set`discussion and compacting URIs to {"@id": "..."} rather than just a string.

**Comment by gkellogg** [comment]
Maybe if the context was something like the following:

```json
{
  "@context": {
    "foo": {"@id": "http://example.com/foo", "@type": "@none", "@container": "@set"},
    "bar": {"@id": "http://example.com/bar", "@type": "@none", "@container": "@set"},
  },
  "@graph": [{
    "foo": [{"@value" : "foo-value"}],
    "bar": [{"@value": "bar-value",  "@language": "en"}]
  }]
}
```

The `"@type": "@none"` could signify that no value compaction should be performed, and the `"@container": "@set"` that values should be represented in an array.

We'd need to figure out the term matching precedence of this over other potentially matching terms, presumably match first.

**Comment by azaroth42** [comment]
`@type: @none` would work for literals, but not for resources per #6, as the algorithm would be unable to distinguish strings containing URIs from URIs.  It would also be harder to distinguish "6" from 6, or 6 from 6.0 if you didn't have a data type.

For consistency with #6, how about (sigh) a new keyword?  `@compactForm: @dict` or something like that?

**Comment by azaroth42** [comment]
There could be two contexts, but I don't know of any project or spec that does that.  I think the cost of a new keyword (or similar) is much lower than making everyone create two contexts if they want this sort of functionality. -0.9

**Comment by gkellogg** [comment]
JSON-LD has always had the notion of expanding an input and re-compacting with a new context, so there's really nothing new here. No new keyword necessary. If you don't like the `expandContext` option, then just make two API calls. Trying to add something that separates the expansion and compaction parts within a single context seems much more of a challenging concept for people to me.

**Comment by azaroth42** [comment]
[WG resolved](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-08-31-json-ld#resolution5) that the use case for #3 and #6 are important, and should have a single solution to be discussed in a separate combined issue:  #33
