### ISSUE TITLE
Missing use of override protected in Expansion

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#301]
[Expansion](https://w3c.github.io/json-ld-api/#expansion-algorithm) step 8 seems to be missing use of a `true` `override protected` argument in the call to the [Context Processing algorithm](https://w3c.github.io/json-ld-api/#context-processing-algorithm).

https://gist.github.com/kasei/c26e10b0defadcc9ab9143782b644087

**Comment by gkellogg** [comment]
@kasei this got lost in some intervening PR, see if this does it.

**Comment by kasei** [comment]
@gkellogg looks good, thanks!
