### ISSUE TITLE
Issue with errors encountered in expansion during toRdf handling

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#303]
toRdf test [twf06](https://w3c.github.io/json-ld-api/tests/toRdf-manifest.html#twf06) uses an invalid datatype IRI:

```json
{
  "@id": "http://example.com/foo",
  "http://example.com/bar": {"@value": "bar", "@type": "http://example.com/baz z"}
}
```

I believe this will fail [Expansion](https://w3c.github.io/json-ld-api/#expansion-algorithm) in step 15.5

However, this test is listed as a PositiveEvaluationTest, and there doesn't seem to be any provision in the JsonLdProcessor Interface to handle errors encountered during expansion. While the expected test output is an empty N-Quads file, I would have thought that an error would not be treated the same as an empty result of quads. Can you please clarify the intention of this test, and whether the text in the [JsonLdProcessor Interface](https://w3c.github.io/json-ld-api/#the-jsonldprocessor-interface) needs updating?

**Comment by gkellogg** [comment]
Yes, I think you're right. It should fail with "invalid typed value".

Note the text at the beginning of the [processor interface](https://www.w3.org/TR/json-ld11-api/#the-jsonldprocessor-interface):

> If an error is detected, the Promise is rejected passing a JsonLdError with the corresponding error code and processing is stopped.

**Comment by gkellogg** [comment]
@kasei These changes should handle such values properly. I added an expansion test, too.

**Comment by gkellogg** [comment]
Resolved to close in [today's meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2020/2020-01-10-json-ld.html#resolution5).
