### ISSUE TITLE
Issue with accessing term definitions in Expansion 11.2

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#304]
[Expansion](https://w3c.github.io/json-ld-api/#expansion-algorithm) step 11.2 says:

> For each `term` which is a value of `value` ordered lexicographically, if `term` is a string, and `term`'s term definition in `active context` has a local context, set `active context` to the result Context Processing algorithm, passing `active context`, the value of the term's `local context` as local context, and `false` for propagate.

I think this text is ambiguous about the order that processing must occur. Based on test [tc018](https://w3c.github.io/json-ld-api/tests/expand-manifest.html#tc018), I believe accessing term definitions from `active context` must occur **outside** of the loop body where `active context` is updated.

If 11.2 is interpreted (incorrectly) as follows, tc018 will fail:

```
for each term in sorted(values of value):
	if term is a string:
		tdef = term_definition(in: active context, for: term)
		if '@context' in tdef:
			active_context = context_processing(active context, tdef['@context'], propagate: false)
```

This will clear `active context` on the first pass of the loop, and there will be no relevant term definition available in the second pass.

**Comment by gkellogg** [comment]
I think what's supposed to happen is to check _term_'s _term definition_ in _type-scoped context_ to see if it has a _local context_, and set _active context_ to the result of processing it from the _active context_, so we don't loose any redifinitions along the way.

More like the following:

    for each term in sorted(values of value):
        if term is a string:
            tdef = term_definition(in: **type-scoped context**, for: term)
		if '@context' in tdef:
			active_context = context_processing(active context, tdef['@context'], propagate: false)

**Comment by gkellogg** [comment]
@davidlehn, WDYT?

**Comment by gkellogg** [comment]
@kasei I used that interpretation described above in PR #307. Please indicate if this adequately addresses the issue.

**Comment by kasei** [comment]
@gkellogg using `type-scoped context` does seem to resolve the issue. If that's the intent, then this change looks good. Thanks.
