### ISSUE TITLE
Clarify text on IRI Expansion in Expansion step 7

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#309]
[Expansion](https://w3c.github.io/json-ld-api/#expansion-algorithm) step 7 should be explicit about how expansion happens for the entry keys of `element`:

> If active context has a previous context , the active context is not propagated. If from map is undefined or false , and element does not contain an entry expanding to `@value` , and element does not consist of a single entry expanding to `@id` , set active context to previous context from active context , as the scope of a term-scoped context does not apply when processing new node objects .

(e.g. whether any of the four optional input variables passed to IRI Expansion.)

**Comment by gkellogg** [comment]
Yes, this is a bit sloppy, but following other patterns leads to excess verbosity. In retrospect, we might have created a glossary of abbreviations for such regular calls, since for keywords, IRI expansion always uses `true` for _vocab_, and by context uses the _active context_ to do the expansion. A longer winded paragraph might read as follows:

> If _active context_ has a _previous context_, the _active context_ is not propagated. If _from map_ is undefined or `false`, and _element_ does not contain an _entry__ expanding to `@value` **(using the IRI expansion algorithm, passing _active context_, that _entry_ for _value_, and `true` for _vocab)**, and _element_ does not consist of a single entry expanding to `@id`  **(using the IRI expansion algorithm, passing _active context_, that _entry_ for _value_, and `true` for _vocab)**, set _active context_ to _previous context_ from _active context_, as the scope of a _term-scoped context_ does not apply when processing new _node objects_.

Is that what you had in mind? Does that add clarity?

**Comment by kasei** [comment]
@gkellogg yes, something like that. Without going to look at the specifics of the expansion algorithm, I would not have been able to tell you that "for keywords, IRI expansion always uses true for vocab", so I've found this sort of explicit language useful where it appears elsewhere in the document.

**Comment by gkellogg** [comment]
@kasei see if that text is clear, and we'll close this.

**Comment by kasei** [comment]
@gkellogg looks good, thanks.
