### ISSUE TITLE
Issue with expansion test t0004

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#310]
Expansion test [t0004](https://w3c.github.io/json-ld-api/tests/expand-manifest.html#t0004) seems to expect the value from the recursive expansion call in 13.4.11.2 to be an array, but it's coming back (from Value Expansion) as a map. This seems related to #299 which would have ensured that the value coming back form the recursive call was an array.

If t0004 represents the expected behavior, does 13.4.11.2 need to duplicate some of the post-processing that #299 moved into the JsonLdProcessor API?

**Comment by gkellogg** [comment]
The result of 13.4.11.2 is, indeed, a map of the form `{"@list": [...]}`, but it will have been invoked from 13.14.2 would have added it to an array value of the associated property.

It is only at the outer level that the API algorithm comes in to place to make sure that the value of there outermost map gets wrapped in an array. Values of properties always get represented as arrays due to 13.14.2.

**Comment by kasei** [comment]
I don't see how 13.14.2 helps here. I believe in this case, the value it will be appending to a list is:

```
{
	"@list": {
		"@value": "one item"
	}
}
```

The list being appended to is `result["http://example.org/property"]`. So we've got this:

```
                'http://example.org/property' => [
                                                   {
                                                     '@list' => {
                                                                  '@value' => 'one item'
                                                                }
                                                   }
                                                 ],
```

But the test is expecting this:

```
                'http://example.org/property' => [
                                                   {
                                                     '@list' => [
                                                                  {
                                                                    '@value' => 'one item'
                                                                  }
                                                                ]
                                                   }
                                                 ],
```

I think the list introduced in 13.14.2 is operating at the wrong level. It needs to happen somewhere between the value being set to `expanded property` in 13.4.11.2 and that value being used to set the `result` entry `@list`-`expanded property` in 13.4.16.

**Comment by gkellogg** [comment]
It looks like 13.4.11.2 should add the words "ensuring that the result is an array." as is done in 13.4.6.

**Comment by gkellogg** [comment]
I actually had a FIXME in my code that this needed to be added! Let me know if that does it.

**Comment by kasei** [comment]
@gkellogg the proposed change too 13.4.11.2 is in fact what I had come up with in attempting to move past this issue, and the wording now matches 13.4.6.2. Looks good.
