### ISSUE TITLE
Possible issue with double-expansion of `@graph` (t0104)

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#311]
[Expansion](https://w3c.github.io/json-ld-api/#expansion-algorithm) step 13.12.1 says:

> If `ev` is not a graph object, convert it into one by creating a map containing the key-value pair `@graph`-`ev` where `ev` is represented as an array.

I believe test [t0104](https://w3c.github.io/json-ld-api/tests/expand-manifest.html#t0104) will reach this point with `ev` **being** a graph object. Therefore 13.12.1 will **not** be used.

However, the test result seems to expect a `@graph` key to be introduced as a result of the container mapping. I can't figure out where this would happen if not here.

(I wonder if this is also related to #299, perhaps expecting the graph node test to fail when the expanded value is an array...?)

**Comment by gkellogg** [comment]
It looks like 13.12.1 should not be conditional, and always make the result a graph object, even if it is already a graph object. @dlongley may remember, but I think this was discussed as being necessary, even though it seems to be doing something twice needlessly.

The new text should say the following:

> Convert `ev` into a graph object by creating a map containing the key-value pair `@graph`-`ev` where `ev` is represented as an array.

**Comment by gkellogg** [comment]
@kasei I believe this is what was intended.

**Comment by kasei** [comment]
As discussed on irc, the new text does not fully capture the intended condition on 13.12. Instead of testing whether `container mapping` *contains* `@graph`, it should be a test for either of two cases:

* `container mapping` contains only `@graph`
* `container mapping` contains only `@graph` and `@set`

**Comment by kasei** [comment]
@gkellogg latest changes in #335 fix this issue. Thanks!
