### ISSUE TITLE
Issue with interpreting integers as doubles in toRdf handling

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#312]
Test [trt01](https://w3c.github.io/json-ld-api/tests/toRdf-manifest.html#trt01) indicates that large integers should be represented as `xsd:double` values in RDF. There is some text that hints at this in section 8.6 [Data Round Tripping](https://www.w3.org/TR/json-ld11-api/#dfn-canonical-lexical-form):

> The canonical lexical form of an integer, i.e., a number with no non-zero fractional part and an exponent less than 21

But I cannot find any algorithmic text (e.g. in [Object to RDF Conversion](https://www.w3.org/TR/json-ld11-api/#object-to-rdf-conversion)) that would implement the interpreting of large integer values as doubles.

Moreover, I'm not sure why the "21" exponent value is special here. There is no text explaining it, and while the text in [Data Round Tripping](https://www.w3.org/TR/json-ld11-api/#dfn-canonical-lexical-form) describes the canonical lexical form of an integer having an exponent less than 21, the [canonical form of integers in XSD Schema 1.1 part 2](https://www.w3.org/TR/xmlschema11-2/#integer-canonical-repr) does not have anything to say about restrictions on exponent values, since the lexical form of XSD integers *does not involve exponents*.

**Comment by pchampin** [comment]
The next paragraph in 8.6 Data Round Tripping says (emphasis is mine):

> The canonical lexical form of a double, *i.e., a number which cannot be represented as an integer*,..

Per the definition of *integer* that you quoted above, this automatically includes numbers with exponent greater than 20.

As for why 21 is the threshold, I have no idea...

**Comment by kasei** [comment]
@pchampin I think there's some confusion about the phrase "represented as an integer," then. `1e21` can be represented as an XSD integer, as well as internally in some languages, so I'm not sure how to interpret the text about doubles with respect to large integers.

**Comment by pchampin** [comment]
> I think there's some confusion about the phrase "represented as an integer," then.

Granted. It would be more accurate to write "a number which is not an *integer* as defined above". Or even clearer, rephrase the (negated) definition: "a number with a non-zero fractional part or an exponent greater than 20".

**Comment by gkellogg** [comment]
The exponent less than 21 comes from [ECMASCRIPT 7.1.12.1](https://www.ecma-international.org/ecma-262/6.0/index.html#sec-tostring-applied-to-the-number-type) by way of [JSON Canonicalization Scheme](https://tools.ietf.org/html/draft-rundgren-json-canonicalization-scheme-05#ref-ES6).

> If k ≤ n ≤ 21, return the String consisting of the code units of the k digits of the decimal representation of s (in order, with no leading zeroes), followed by n−k occurrences of the code unit 0x0030 (DIGIT ZERO).

Otherwise, I'm happy with @pchampin's suggested update.

**Comment by pchampin** [comment]
@kasei Are you satisfied with #317 above?
Should I also add a note explaining where the 21 exponent come from?

**Comment by gkellogg** [comment]
It's probably worth adding something about JCS, at least. It's impossible to completely separate JSON from ECMASCRIPT, and the two are constantly kept in sync by IETF.

**Comment by kasei** [comment]
@pchampin While #317 might be helpful, it doesn't address the main issues. I believe they remain:

* No algorithmic process for turning integers into xsd:doubles in Object to RDF Conversion
* The inclusion of language about exponents in a section that seems to canonically link to XSD (in which domain integers have nothing to do with exponents)

**Comment by pchampin** [comment]
> No algorithmic process for turning integers into xsd:doubles in Object to RDF Conversion

Actually, [Object to RDF Conversion] never deals with integers, but it deals with [numbers](https://tc39.es/ecma262/#sec-terms-and-definitions-number-value) which by definitions *are* double.

> The inclusion of language about exponents [is required]

I agree. I suggest to replace the conditions on the exponent (greater or less than 21) to a comparison to 10^21 -- which should be equivalent, unless I'm mistaken. @gkellogg, what do you think?

Now, regarding [trt01], I don't see how `1e21` should end up with the datatype `xsd:double`. Following the algorithm in [Object to RDF Conversion],

* it does not match the condition in step 10 (which produces `xsd:double`),
* it does match the condition in step 11, which produces `xsd:integer`.

Even worth, in that case, step 11 is contradictory: it says that the canonical lexical form of `xsd:integer` should be used, but then [Data Round Tripping] generates `1e21`, which is *not* in the lexical space of `xsd:integer`.

It seems to me that step 10 should "catch" numbers with no non-zero fractional part but which are ≥ 10^21.

[Data Round Tripping]: https://www.w3.org/TR/json-ld11-api/#data-round-tripping
[Object to RDF Conversion]: https://www.w3.org/TR/json-ld11-api/#object-to-rdf-conversion
 [trt01]: https://w3c.github.io/json-ld-api/tests/toRdf-manifest.html#trt01

**Comment by kasei** [comment]
> Actually, Object to RDF Conversion never deals with integers, but it deals with numbers which by definitions are double.

Yes. What I probably should have said was no algorithm process for turning numbers with no non-zero fractional part into `xsd:double`s when they are "large" (≥10^21.)

> I suggest to replace the conditions on the exponent (greater or less than 21) to a comparison to 10^21 -- which should be equivalent, unless I'm mistaken.

I think that would be a good change, and also agree with your assessment on steps 10 and 11.

**Comment by gkellogg** [comment]
> > No algorithmic process for turning integers into xsd:doubles in Object to RDF Conversion
> 
> Actually, [Object to RDF Conversion](https://www.w3.org/TR/json-ld11-api/#object-to-rdf-conversion) never deals with integers, but it deals with [numbers](https://tc39.es/ecma262/#sec-terms-and-definitions-number-value) which by definitions _are_ double.
> 
> > The inclusion of language about exponents [is required]
> 
> I agree. I suggest to replace the conditions on the exponent (greater or less than 21) to a comparison to 10^21 -- which should be equivalent, unless I'm mistaken. @gkellogg, what do you think?

👍 

Yes, additionally, step 10 of Object to RDF Conversion needs to factor in numbers with non-zero exponents and which are >= 10<sup>21</sup> (or `1E21` using the canonical representation).

> Now, regarding [trt01](https://w3c.github.io/json-ld-api/tests/toRdf-manifest.html#trt01), I don't see how `1e21` should end up with the datatype `xsd:double`. Following the algorithm in [Object to RDF Conversion](https://www.w3.org/TR/json-ld11-api/#object-to-rdf-conversion),
> 
> * it does not match the condition in step 10 (which produces `xsd:double`),
> * it does match the condition in step 11, which produces `xsd:integer`.

See above, step 10 should be updated to cover this.

> Even worth, in that case, step 11 is contradictory: it says that the canonical lexical form of `xsd:integer` should be used, but then [Data Round Tripping](https://www.w3.org/TR/json-ld11-api/#data-round-tripping) generates `1e21`, which is _not_ in the lexical space of `xsd:integer`.
> 
> It seems to me that step 10 should "catch" numbers with no non-zero fractional part but which are ≥ 10^21.

👍

**Comment by pchampin** [comment]
I pushed the suggested changes in #317. Note that the 'preview/diff' features does not seem to like the force push, it is not up-to-date...

Actually, the test should be on the *absolute value* of the number, that's what I wrote. Also, I kept the "mathematical" spelling of 10^21 rather than `1E21` because I didn't want to give the impression that the float/double datatype was assumed here.

Finally, I also simplified step 11 of "Object to RDF Conversion":

* changed the condition "if value is a number with no non-zero fractional part" to "if value is a number",
  because any number with a non-zero fractional part would have been caught by step 10 anyway;
  moved that part to a note

* removed the subcondition "if value is a number and datatype is xsd:integer", because, as pointed out above, between step 10 and the first condition in step 11, any number has already been caught... So this subcondition was effectively never met.

**Comment by gkellogg** [comment]
@pchampin do we need changes to tests?

**Comment by pchampin** [comment]
@gkellogg I dont think we do. I didn't mean to change the behaviour of the algorithm, only make it clearer.
(well, except for catching big integera in step 10, but there was already a teat for that 😉 )

**Comment by pchampin** [comment]
@kasei does the latest changes in #317 fully address the issue?

**Comment by kasei** [comment]
@pchampin yes, I think that looks good. Thanks!
