### ISSUE TITLE
Issue with IRI Compaction language regarding authorities

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#314]
[IRI Compaction](https://w3c.github.io/json-ld-api/#algorithm-7) step 7 says:

> `var` has no [IRI authority](https://tools.ietf.org/html/rfc3986#section-3.1) (beginning with double-forward-slash (`//`)

There are a couple of issues here:

* The "IRI authority" text links to the section in the IRI spec for schemes, not authorities
* IRI authorities do not begin with `//`, they are merely preceded by it (https://tools.ietf.org/html/rfc3986#section-3.2). If the intention of this text is to test if `var` does *not* begin with scheme followed by `://`, I think the wording could be improved here.

**Comment by gkellogg** [comment]
Yes, should point to 3.2. However, the language otherwise seems right, as by definition, if it has an _authority_ it is proceeded by a double-forward slash, so the test is to see if it does _not_ have an authority.

From the RFC:

> The authority component is preceded by a double slash ("//") and is
   terminated by the next slash ("/") ...

**Comment by kasei** [comment]
@gkellogg I find the "beginning with double-forward-slash" confusing because the "beginning" here seems to apply to the "authority", and can't apply to the IRI as a whole, because in this case there is a scheme, and so the IRI necessarily begins with something before the "//".

**Comment by gkellogg** [comment]
how about s/beginning with/preceded by/?
