### ISSUE TITLE
Argument naming issue in Compaction

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#316]
[Compaction](https://w3c.github.io/json-ld-api/#algorithm-6) step 12.8.1 calls [IRI Compaction](https://w3c.github.io/json-ld-api/#iri-compaction):

> passing `active context`, `inverse context`, `expanded property` for `var`, `expanded item` for `value`, `true` for `vocab`, and `inside reverse`.

Presumably this last argument should be "`inside reverse` for `reverse flag`", as the variable and argument have different names?

**Comment by gkellogg** [comment]
@kasei fixed in #325.

**Comment by kasei** [comment]
@gkellogg looks good. Thanks.
