### ISSUE TITLE
Return type of Compaction Algorithm

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#318]
[Compaction overview](https://w3c.github.io/json-ld-api/#overview-6) says:

> The final output is a map with an @context entry, if a non-empty context was given, where the map is either result or a wrapper for it where result appears as the value of an (aliased) @graph entry because result contained two or more items in an array.

However, the actual algorithm can return non-maps. For example, trivial paths that return non-paths are found ending at steps 2 (string) and 3.4 (array).

This seems to be because Compaction has trailing text that changes the return value (similar to previous versions of the Expansion Algorithm). I would suggest that if the intent here is the same as for Expansion (a post-processing step not meant to apply to recursive calls), that this trailing text be moved into the JsonLdProcessor Interface section (similar to #299).

**Comment by gkellogg** [comment]
@kasei I made essentially the same change here as for compaction in PR #336.

**Comment by kasei** [comment]
@gkellogg I notice that compaction also has leading text that might make sense in JsonLdProcessor also (text beginning "To begin"). What do you think?

**Comment by gkellogg** [comment]
I moved that as well as some lingering pre-processing in Expansion.
