### ISSUE TITLE
Issue with algorithm text in Value Compaction

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#321]
[Value Compaction](https://w3c.github.io/json-ld-api/#value-compaction) step 4.1 begins:

> If `value` and the `type mapping` of `active property` is set to `@id`...

I'm not sure how to interpret this language. Is it a three-way equality test? Or is there a missing clause at the beginning regarding `value`?

**Comment by gkellogg** [comment]
As discussed on IRC, the "_value_ and" has no use in this comparison. Additionally, 4.2 should be conditional on _type mapping_ set to `@vocab`, and there should be a 4.3 that handles the case when its neither.

**Comment by gkellogg** [comment]
@kasei fixed in #326.

**Comment by kasei** [comment]
@gkellogg looks good. Thanks.
