### ISSUE TITLE
Confused type of variable in Compaction Algorithm

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#322]
[Compaction](https://w3c.github.io/json-ld-api/#algorithm-6) step 12.8.3 sets `container` to either `null` or a scalar value:

> Initialize `container` to `null`. If there is a container mapping for `item active property` in `active context`, set `container` to the first such value other than `@set`.

Some steps (e.g. 12.8.6.2, 12.8.8.8) treat `container` as a scalar value in comparisons. However, some subsequent steps seem to treat it as a composite value (an array?):

* 12.8.7.1: "If `container` includes `@graph` and `@id`"
* 12.8.7.2: "Otherwise, if `container` includes `@graph` and `@index` and `expanded item` is a simple graph object"

And others where the language is for a composite value ("includes"), even if only one value is being tested:

* 12.8.7.3
* 12.8.7.4
* 12.8.8
* 12.8.8.4
* 12.8.8.5
* 12.8.8.6
* 12.8.8.7

**Comment by gkellogg** [comment]
Yes language should be updated to consistently use an array form and either compare based on inclusion, or that the array value is exactly a given value (possibly including `@set`).

**Comment by kasei** [comment]
@gkellogg how am I to understand "the first such value" in the context of setting `container` to an array that may have multiple values?

**Comment by gkellogg** [comment]
I don’t think that phrasing is necessary, in retrospect, as we have no implied over if containers.

Ordering does come into play in term selection, but there we sort them and concatenate into a string form.

**Comment by kasei** [comment]
So `container` should be the entire container mapping? Or the container mapping filtered so as to remove `@set`?

**Comment by gkellogg** [comment]
It is probably the case that we can continue to use _includes_ everywhere, as the cases where it may contain `@set`, or something else, are likely handled by the syntactic requirements enforced in Create Term Definition; I'll investigate.

**Comment by gkellogg** [comment]
@kasei the updated language in PR #338 should handle it.
