### ISSUE TITLE
Missing variable name in Compaction 12.8.7.4.5

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#323]
[Compaction](https://w3c.github.io/json-ld-api/#algorithm-6) step 12.8.7.4.5 says:

> Then append `compacted item` to the value if `compacted item` is not an array, otherwise, concatenate it.

This seems to be missing text about which array the value(s) are meant to be appended to.

**Comment by gkellogg** [comment]
@kasei fixed in #325.

**Comment by kasei** [comment]
@gkellogg the text now reads:

> Then append `compacted item` to the value if `compacted item` is not an array , otherwise, concatenate `compacted item` to the value. 

I'm still unclear on what "the value" refers to.

**Comment by gkellogg** [comment]
I'm going to defer this to #332.
