### ISSUE TITLE
Missing variable name in Compaction 12.8.7.4.2 and 12.8.7.4.3

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#324]
[Compaction](https://w3c.github.io/json-ld-api/#algorithm-6) step 12.8.7.4.2 says:

> If expanded item contains an @id entry, add the key resulting from calling the IRI Compaction algorithm passing active context, inverse context, @id as var, and true for vocab using the value resulting from calling the IRI Compaction algorithm passing active context, inverse context, the value of @id in expanded item as var.

This seems to be missing text about which map is to be updated with the specified key and value.

The same issue appears in 12.8.7.4.3.

**Comment by gkellogg** [comment]
@kasei fixed in #325.

**Comment by kasei** [comment]
@gkellogg Thanks. The resulting text here ends up being pretty dense (45 words between "add" and "to compacted item"). Might be nice if there was a way to improve that, but I won't hold up the issue over it. Thanks.

**Comment by gkellogg** [comment]
I'll do this as part of #332. This is an opportunity to create some general definitions for things like "compact the item" that can be used as "macros" to reduce the boilerplate in such steps.
