### ISSUE TITLE
Unclear language in Compaction Algorithm

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#327]
[Compaction](https://w3c.github.io/json-ld-api/#algorithm-6) step 12.8.7.4 says:

> Otherwise, `container` does not include `@graph` or otherwise does not match one of the previous cases, redo `compacted item`.

The language here is unclear:

* Is this meant to be an "else if" (e.g. there is a missing "if" after "Otherwise,")?
* Is the "otherwise does not match one of the previous cases" language just a restating of the initial "Otherwise"?
* It's not clear what "redo `compacted item`" means here

**Comment by gkellogg** [comment]
The remainder after "Otherwise" is simply a statement of the conditions that led to this point, and that the following steps will redo the compacted item. It could be made a parenthetical, if you feel that would improve it, or made into a note.

**Comment by gkellogg** [comment]
This is addressed in PR #339.

**Comment by kasei** [comment]
@gkellogg #339 looks good for this. Thanks.
