### ISSUE TITLE
Possible missing language in Value Compaction 4.2

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#328]
Value Compaction step 4.2:

> Otherwise, the type mapping of `active property` is set to `@vocab`, set `result` to the result of using the IRI compaction algorithm, passing `active context`, `inverse context`, the value of the `@id` entry for `var`, and `true` for `vocab`.

Is this missing an "if" (e.g. "Otherwise, if...")? This would seem natural as following similar language in 4.1.

**Comment by gkellogg** [comment]
This was handled in #326 which was a response to #321.
