### ISSUE TITLE
Ambiguous language in Compaction 12.8.6.2.2

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#329]
Compaction step 12.8.6.2.2:

> If `expanded item` contains the entry `@index`, then add an entry to `compacted item` where the key is the result of the IRI Compaction algorithm, passing `active context`, `inverse context`, `@index` as var, and the value associated with the `@index` entry in `expanded item` as value.

This text is confusing as `value` can be interpreted in two ways:

* As the value of the entry being set in `compacted item`
* As an optional argument to the IRI Compaction Algorithm

**Comment by gkellogg** [comment]
As part of #322, I'll create algorithmic terminology to reduce the boilerplate text for calling IRI Compaction algorithm to something like the following:

> If expanded item contains the entry @index, then add an entry to compacted item where the key is the result _iri compacting_ `@index`, and the value is value of the `@index` entry in _expanded item_.

Then _iri compacting_ can be defined as an invocation of the IRI Compaction Algorithm using _active context_ (or some other explicit provided context), _inverse context_, and `vocab: true` with a provided argument.

The pattern for adding entries is to specify the _key_ and _value_ of the entry, so in this case the first _value_ refers to that new entry.

Do you think there is some standardized markup that would clarify adding such entries?

This should clean up many of these confusing statements where you can get lost in the boilerplate.

**Comment by gkellogg** [comment]
Updated in PR #339.

**Comment by kasei** [comment]
@gkellogg #339 looks good for this. Thanks.
