### ISSUE TITLE
Imprecise language referring to variable in Compaction Algorithm

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#330]
[Compaction](https://w3c.github.io/json-ld-api/#algorithm-6) step 12.8.9.1 says:

> If `compactArrays` is false, `as array` is true and `compacted item` is not an array, set it to a new array containing only `compacted item`.

Assuming "it" here is in reference to `compacted item`, it would be much clearer to state this explicitly.

**Comment by gkellogg** [comment]
Changes in PR #339 include updates that address this.
