### ISSUE TITLE
Possible context syntax error tests

### ISSUE THREAD

**Issue by davidlehn** [w3c/json-ld-api#331]
How deeply should contexts be checked, even if not used?  I was noticing the odd behavior in jsonld.js 2.0.1 of the following.

Missing t1 and t2 ids, no data, syntax error `"@context terms must define an @id."`:
```json
{
  "@context": {
    "@version": 1.1,
    "t1": {
      "@context": {
        "t2": {
          "@context": {
            "type": null
          }
        }
      }
    }
  }
}
```

Missing a t2 id, no data, works:
```json
{
  "@context": {
    "@version": 1.1,
    "t1": {
      "@id": "ex:t1",
      "@context": {
        "t2": {
          "@context": {
            "type": null
          }
        }
      }
    }
  }
}
```

Missing t2 id, t1 used, syntax error `"@context terms must define an @id."`:
```json
{
  "@context": {
    "@version": 1.1,
    "t1": {
      "@id": "ex:t1",
      "@context": {
        "t2": {
          "@context": {
            "type": null
          }
        }
      }
    }
  },
  "t1": {"t2": "x"}
}
```

Has t1 and t2 ids, works with or without data:
```json
{
  "@context": {
    "@version": 1.1,
    "t1": {
      "@id": "ex:t1",
      "@context": {
        "t2": {
          "@id": "ex:t2",
          "@context": {
            "type": null
          }
        }
      }
    }
  },
  "t1": {"t2": "x"}
}
```

I'm guessing this is exposing quirks of jsonld.js. Should it always be checking for those syntax errors in the context, regardless of the data?  Looks like some test coverage may be needed for this.

**Comment by gkellogg** [comment]
Step 23 of the [Create Term Definition Algorithm](https://w3c.github.io/json-ld-api/#create-term-definition) recurses into `@context` within a term definition specifically to make sure it's valid, as it needs to be re-processed during compaction and expansion.

I think, at least when in validation mode, you should run this step to recursively find such errors before the contexts are used. (They may never be used).

Adding a test that checks for this would be useful.
