### ISSUE TITLE
Use of undefined variable in Inverse Context Creation

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#342]
[Inverse Context Creation](https://w3c.github.io/json-ld-api/#algorithm-1) step 3.14 says:

> If `language map` does not have a `lang dir` entry, create one and set its value to the term being processed.

However, `lang dir` is only initialized *conditionally* in 3.13.1. If that condition fails, and 3.13.1 is never processed, what is the interpretation of the use of `lang dir` in 3.14?

**Comment by gkellogg** [comment]
It should have been inside the ordered list, not outside.

**Comment by kasei** [comment]
#344 looks good. Thanks.
