### ISSUE TITLE
IRI Compaction possibly missing type checks when using value as a map

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#348]
[IRI Compaction](https://w3c.github.io/json-ld-api/#algorithm-7) step 2.11 says:

> If `processing mode` not `json-ld-1.0` and `value` does not contain an `@index` entry, append `@index` and `@index@set` to `containers`.

(I'm assuming "`processing mode` not `json-ld-1.0`" is missing an "is": "*is* not `json-ld-1.0`"?)

Steps 2.2 and 2.5 seem to condition entry checking on `value` being a map ("If value is a map containing the entry..."). Should 2.11 be doing this as well?

**Comment by gkellogg** [comment]
For consistency, but _value_ will always be a map if it is provided.

**Comment by gkellogg** [comment]
Other place use wording like "`@index` is not an entry in _value_`" which is more economical, and it can be inferred that _value_ must be a map for it to have an "entry", particularly is marked up to reference the "map entry" definition.
