### ISSUE TITLE
Incorrect markup for variables in IRI Compaction step 5

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#349]
[IRI Compaction](https://w3c.github.io/json-ld-api/#algorithm-7) step 5 uses markup that conflates variable names and "JSON-LD Specific Term Definitions" for the variables `term` and `term definition`.

**Comment by kasei** [comment]
@gkellogg the change in #352 seems to change the wording (and possibly semantics?) of step 5. The previous version compared `term definition` and `null`, while the new one just compares the `IRI mapping` *from* the term definition to `null`. Is that a meaningful change?

**Comment by gkellogg** [comment]
The description for “term definition” describes it as an entry level j a context that has a key (term) and other entries itself. It may be that a map in a context for term definitions would have a term key with a null value, or a term key with a term definition with a null IRI mapping, which are both equivalent. But, a “term definition” is its own thing, and in that context it doesn’t make sense to say that it’s value is null.
