### ISSUE TITLE
Handling of @value-only maps in Value Compaction

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#351]
The [Value Compaction Overview](https://w3c.github.io/json-ld-api/#overview-8) says:

> [Compacting `value` just into the value associated with the `@value` entry] can also be done if `@value` is the only entry in `value` (apart an `@index` entry in case the `container mapping` of `active property` includes `@index`) and either its associated value is not a string, there is no default language, or there is an explicit `null` language mapping for the active property.

However, I can't see any place in the algorithm that handles the specific of a `value` with only a `@value` entry whose value is not a string. Step 7.1 seems to get close, but requires "an `@index` entry, and the `container mapping` associated to `active property` includes `@index`".

**Comment by kasei** [comment]
@gkellogg the new wording in #352 for Value Compaction 7.1 does not seem like it does what the overview section describes. Instead of checking if the value has only `@value` and an optional `@index`, it is adding only a check for the absence of `@index`.

While my test coverage on compaction is rather dismal at this point, implementing the changes in #352 leaves me with ~30 more failing tests than this attempt at implementing the overview language:

> If `value` has an `@index` entry , and the `container mapping` associated to `active property` includes `@index`, or if `value` has only one entry and that entry's key is `@value`...

(I believe there's no need to check that the single entry is `@value` since step 7 implies that such a value exists but is not a string, but I've included the explicit language here anyway.)

Thoughts?

**Comment by gkellogg** [comment]
By the time we get to step 7, _value_ has `@value` and may have `@index`, `@language`, and/or `@direction`. In the case of step 7, it has `@value` and may have `@index` and the value of `@value` is not a string. If the term definition for _active property_ uses `@container: @index`, and it has an `@index` entry, then it can be represented using just the value of `@value`. The same if it includes only `@value` (it can't not be a string and include `@language` or `@direction`).

Step 8 is much the same, if the value matches the language and direction, then if it has `@index` we can use just the value of `@value` if the _active property_ also uses `@container: @value`, or if it doesn't have an `@index`, so the two are treated pretty much the same.

By the time we get to step 9 either _result_ is a map, in which case we compact keys, or it is a scalar value, in which case it is returned as is.

This seems to match the description to me (it also fairly closely matches [my implementation](https://github.com/ruby-rdf/json-ld/blob/1433d521f000d04f94691efc8d2760faff1232e0/lib/json/ld/context.rb#L1722-L1724)). The wording may be backwards, but the affect is the same.

**Comment by gkellogg** [comment]
@kasei still waiting to see if this solves the issue for you.

**Comment by kasei** [comment]
@gkellogg Yeah. I implement it slightly differently, but based on your explanation, I think this wording is probably fine.
