### ISSUE TITLE
Missing type checking of values in IRI Compaction?

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#357]
In several places, the [IRI Compaction algorithm](https://w3c.github.io/json-ld-api/#algorithm-7) seems to assume that the `value` variable is a map. For example, in step 2.11:

> If `processing mode` is not `json-ld-1.0` and `value` does not contain an `@index` entry, append `@index` and `@index@set` to `containers`.

Step 2.5 seems to have what might have been an attempt at verifying that `value` is a map, but with missing language or markup:

> If `@index` is an entry in `value` is a map, and `value` is not a graph object then append the values `@index` and `@index@set` to `containers`.

However, IRI Compaction can be called with non-map values of `value`, as in [Compaction](https://w3c.github.io/json-ld-api/#algorithm-6) steps 12.7 and 12.7.1:

> 12.7) If `expanded value` is an empty array:
> 12.7.1) Initialize `item active property` by IRI compacting `expanded property` using `expanded value` for value and `inside reverse` for reverse.

Should IRI Compaction have better type checking? Is there a mistake in the argument value in12.7.1?

**Comment by gkellogg** [comment]
There is some shortcutting, a value can only contain an entry if it is a map, so it is somewhat redundant to first check that it is a map to see if it contains an entry.

**Comment by kasei** [comment]
2.5 still seems to be missing a word. Should it be "If @index is an entry in value *and its value* is a map"?

Understood about the shortcutting, but I'll note that there are other places in the document that seem to include such type checking language, including:

* [Expansion](https://w3c.github.io/json-ld-api/#expansion-algorithm) step 19.1 and 19.2:

  > 19.1) If `result` is a map which is empty, or contains only the entries `@value` or `@list`, set result to null.
  > 19.2) Otherwise, if `result` is a map whose only entry is `@id`, set `result` to `null`.

* [API compact()](https://w3c.github.io/json-ld-api/#dom-jsonldprocessor-compact) step 3:

  > If `context` is a map having an `@context` entry, set `context` to that entry's value, otherwise to `context`.

* [API expand()](https://w3c.github.io/json-ld-api/#dom-jsonldprocessor-expand) steps 5 and 7.1:

  > 5) If `expandContext` is a map having an `@context` entry, pass that entry's value instead.
  > 7.1) ... If `expanded output` is a map that contains only an `@graph` entry, set `expanded output` that value.

Personally, I find this type checking language helpful, as it removes uncertainty about what the expected type of the value is, and indicates whether guarding the step with type checking is necessary. Such language is also symmetric with existing spec language such as "Otherwise element is a map" (Expansion step 6) which makes explicit the known type of the value.

**Comment by kasei** [comment]
🤨 FYI, GitHub markdown seems to have mangled the step numbers in that final list item.

**Comment by gkellogg** [comment]
Okay, see if #360 is satisfactory.
