### ISSUE TITLE
Confusing/contradictory text regarding options passed to Compaction

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#358]
The definition of `compact()` in [The JsonLdProcessor Interface](https://w3c.github.io/json-ld-api/#the-jsonldprocessor-interface) section calls the Compaction algorithm:

> using `active context`, `inverse context`, `null` for `active property`, `expanded input` as `element`, and if passed, the `compactArrays` and `ordered` flags in `options`.

I find the "if passed" text confusing here. `options` is defined as:

> A set of options to configure the algorithms. This allows, e.g., to set the input document's base IRI.

It wasn't immediately clear to me that `options` is full [JsonLdOptions Type](https://w3c.github.io/json-ld-api/#the-jsonldoptions-type), with all the default values as specified in section 9.3. For that reason, I missed the fact that `compact()` needs to pass the default value of `compactArrays` as `true` to the Compaction algorithm. An explicit link between `compact()` and the `JsonLdOptions Type` section would help to clarify this. 

Further confusing the issue, the [Compaction Algorithm](https://w3c.github.io/json-ld-api/#algorithm-6) says:

> The optional inputs are the `compactArrays` flag and the `ordered` flag, used to order map entry keys lexicographically, where noted. If not passed, the both flags are set to `false`.

It's not clear to me if this `false` default value can ever be used since calls to the algorithm seem to always need a full options structure, in which `compactArrays` must have a value.

**Comment by gkellogg** [comment]
This language is cleaned up in PR #362.

**Comment by kasei** [comment]
@gkellogg This seems like an improvement, but not a fully realized fix.

The language about default values for the "optional" flag values in Expansion is removed from section 5.1.2. This suggests that they may not actually be optional. However, the recursive calls in these steps all seem to pass two of the three flags (missing the "from map" flag):

* 13.4.5
* 13.4.6.2
* 13.4.11.2
* 13.4.12
* 13.4.13.2
* 13.4.15
* 13.8.3.6
* 13.9

Similar issues may affect the other algorithms (e.g. describing arguments as "optional" but either using them as required or not describing how to treat optional values that are not supplied).

**Comment by gkellogg** [comment]
Yes, I was hasty in removing the "If not passed" language. You're right, that as used, the fact that they're optional is not significant, but I think it's still worth describing them as optional.

It is reasonable that "from map" is not set explicitly on each call, as it really only relates to that specific call.
