### ISSUE TITLE
Use mf:requires for optional test behavior

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-api#365]
See https://github.com/w3c/json-ld-api/issues/337#issuecomment-579538330. This would be useful for `rdfDirection` and HTML processing.

**Comment by kasei** [comment]
Would this be useful for tests involving "generalized RDF"? I build on a stack that has no support for such data, so currently try to key off of the `produceGeneralizedRdf` `option` in the test manifests. It would be nice to have that explicitly indicated as a required feature to be able to evaluate the test.

**Comment by gkellogg** [comment]
Yes, we should add something for generalizedRdf, HTML and the variations on base direction.

**Comment by davidlehn** [comment]
If feature flags are being designed, might be useful if they could also be used for a formal or informal implementation feature detection API for general application use.

**Comment by gkellogg** [comment]
The SPARQL `mf:requires`, and it's various values, are described [here](https://github.com/w3c/rdf-tests/tree/gh-pages/sparql11).

**Comment by gkellogg** [comment]
@kasei see #368.
