### ISSUE TITLE
redundant framing keyword

### ISSUE THREAD

**Issue by roptat** [w3c/json-ld-api#367]
In 13.4.15, the document says "When the frameExpansion flag is set, if expanded property is any other framing keyword (`@explicit`, `@default`, `@embed`, `@explicit`, `@omitDefault`, or `@requireAll`), set expanded value to the result of performing the Expansion Algorithm recursively, passing active context, active property, value for element, and the frameExpansion and ordered flags."

It lists `@explicit` twice.

**Comment by roptat** [comment]
oh, sorry for the mentions :/

**Comment by BigBlueHat** [comment]
> oh, sorry for the mentions :/

@roptat it happens. 😄 I've edited your initial comment and put tick marks (`) around them. That seems to avoid the mentions.
