### ISSUE TITLE
Suggested link target improvement in Context Processing

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#371]
(Related to #265, #356)

The link in [Context Processing](https://w3c.github.io/json-ld-api/#algorithm) step 5.1.2 "base IRI" should link to the active context definition.

**Comment by gkellogg** [comment]
There is no specific definition for _active context_ _base IRI_ field, as there is for _original base URL_. This is also true for _vocabulary mapping_, _default language_, and _default base direction_. The next of 5.1.2 makes clear that this is for that field in the _active context_.

I don't think it wise or necessary to add separate definitions for fields of such data structures. An alternate way would have been to define WebIDL structures for _active context_ and _term definition_ which does allow for structure-specific addressing, but we decided to not go there for these relatively few internal structures.

**Comment by kasei** [comment]
Maybe I'm misunderstanding. (The grammatical structure of 5.1.2 is *very* confusing.) Is the base IRI being updated in 5.1.2 *not* the same as "the current base IRI (IRI)" defined as being part of an active context?

**Comment by gkellogg** [comment]
We  initialize a new _active context_ and set _base IRI_ and _original base IRI_ fields to the value of _original base IRI_ in the existing _active context_. (Along with _previous context_).

```
previousResult = result
result = ActiveContext.new
if !_propagate_
  result.previousContext = previousResult
result.baseIRI = activeContext.originalBaseUrl
result.originalBaseUrl = activeContext.originalBaseUrl
```

**Comment by kasei** [comment]
Right. So I'd suggest improving the language to not have those two assignments directly follow a conditional clause without any punctuation.

But beyond that, Isn't `result.baseIRI` in your code a reference to "the current base IRI" defined in [section 4.1](https://w3c.github.io/json-ld-api/#context-processing-algorithm) (immediately preceding the definition for [the original base URL](https://w3c.github.io/json-ld-api/#dfn-original-base-url))?

**Comment by gkellogg** [comment]
I'll reorder the clauses in the sentence to make it clear that the conditional only applies to _previous context_.

In the pseudo-code, and in the algorithm, `result` has been set to a new _active context_, so `base URI`, refers to the `base URI` associated with that _active context_. As mentioned above, there is no specific definition for that field within a _base context_, other than what is described in 4.1. IMO, it's clear in this context what is meant when we say we're initializing a new _active context_ and setting some values within that _active context_.

**Comment by gkellogg** [comment]
Updated in #377.

**Comment by kasei** [comment]
> there is no specific definition for that field within a base context, other than what is described in 4.1.

I'm not asking for anything beyond a link to 4.1. But currently "original base URL" links to 4.1 while "base IRI" links to RDF 1.1 Concepts and Abstract Syntax. Since the item "the current base IRI" in 4.1 also links to RDF 1.1 Concepts and Abstract Syntax, I'm asking why step 5.1.2 links directly to RDF 1.1 Concepts and Abstract Syntax instead of to 4.1.

(I'm also not sure what "base context" refers to here.)

**Comment by gkellogg** [comment]
On advice, we limited local definitions of terms to those that are truly JSON-LD-specific terms, and refer to the defining specs when using terms that are originally defined elsewhere. This is the case for `base IRI`.

In this case, maybe it would be best to change the field in _active context_ to _base URL_ to not confuse it. It would probably be better for both this, and _original base URL_ to not be exported as outside referencable terms.

**Comment by gkellogg** [comment]
Stuck with the name _base IRI_, but it is now a definition with the fragment identifier _context-base-iri_.

**Comment by gkellogg** [comment]
Updated in #377.
