### ISSUE TITLE
Use of possibly undefined variables in Context Processing

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#372]
(Related to #265, #356)

[Context Processing](https://w3c.github.io/json-ld-api/#algorithm) step 5.2.5 uses `loaded context` which is only defined in 5.2.4.3 (which is not necessarily evaluated prior to 5.2.5)

[Context Processing](https://w3c.github.io/json-ld-api/#algorithm) step 5.2.5 uses `context document` which is only defined in 5.2.4 (which is not necessarily evaluated prior to 5.2.5)

**Comment by gkellogg** [comment]
Updated in #377.

**Comment by kasei** [comment]
@gkellogg new language in #377 looks good for this. Thanks.
