### ISSUE TITLE
Missing use of required Expansion input variable in expand()

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#374]
(Related to #265, #356)

[`expand()`](https://w3c.github.io/json-ld-api/#dom-jsonldprocessor-expand) step 7:

> Set expanded output to the result of using the Expansion algorithm, passing the active context, document from remote document or input if there is no remote document as element, documentUrl as base URL, and frameExpansion and and ordered flags from options.

Expansion 5.1.2 says `active property` is a required input variable, but it is not supplied at this callsite.

**Comment by gkellogg** [comment]
Updated in #377.

**Comment by kasei** [comment]
@gkellogg #377 looks good. Thanks.
