### ISSUE TITLE
expansion final steps

### ISSUE THREAD

**Issue by roptat** [w3c/json-ld-api#378]
Hi, I'm trying to implement the expansion algorithm, but I'm having some troubles with the last steps. Specifically, the steps 17 and 20 makes it impossible for me to pass this test: https://w3c.github.io/json-ld-api/tests/expand/0008-in.jsonld.

At some point I have the object `{"@language": "en"}` which, as per 17, becomes `null`. Then, as per step 20, it becomes `[]` and this is what is then associated to drop-lang-only, instead of `null` which would have made it be dropped. In jsonld 1.0, some of these last steps were only done for the top-level element we were expanding, not when using the algorithm recursively. Am I missing something?

**Comment by gkellogg** [comment]
This has been updated in the [editor's draft](https://w3c.github.io/json-ld-api/#expansion-algorithm). We will be re-issuing the CR in the coming weeks.

Step 18 now returns `null`, and returns to 13.10, which skips the key if the result is `null`.

**Comment by roptat** [comment]
oh, thanks! you can close this then :)
