### ISSUE TITLE
term mapping to @type: invalid IRI mapping

### ISSUE THREAD

**Issue by roptat** [w3c/json-ld-api#385]
Hi, I'm still trying to implement jsonld :)

This time I updated my implementation to the latest draft and I think I found an issue in the create term definition algorithm:

This file: `https://w3c.github.io/json-ld-api/tests/expand/0026-in.jsonld` will create a term definition for `http://www.w3.org/1999/02/22-rdf-syntax-ns#type`. In step 14 (since it has an `@id`), it will set its IRI mapping to `@type`, and in 14.2.4.2 it will use the IRI expansion algorithm on the term itself. However, the active context is still empty at this point, and since the term is already an IRI, it will be returned as is, which is different from `@type`, resulting in an invalid IRI mapping error.

**Comment by gkellogg** [comment]
That test is obsoleted for JSON-LD 1.1, note the option `"specVersion": "json-ld-1.0"`.

**Comment by roptat** [comment]
alright, I added support for the `specVersion` to my tests, so it removed that test and others. Sorry for the troubles, I suppose this can be closed. When you mark `propose closing`, does it mean I'm supposed to close or is it intended for someone else?

**Comment by gkellogg** [comment]
Just a status to manage issues. Since you agree, I’ll close. As we’re in the CR phase, things get more formal.
