### ISSUE TITLE
@reverse and keyword form

### ISSUE THREAD

**Issue by roptat** [w3c/json-ld-api#386]
So, for test [pr39](https://w3c.github.io/json-ld-api/tests/expand/pr39-in.jsonld), the expected result is an invalid IRI mapping error, but I don't think this is what the specification says, and the playground agrees with me.

Since we have `"@reverse": "@ignoreMe"`, a reverse property associated with a string that has the form of a keyword, step 13.3 says that we should ignore the `@reverse` and return. Step 13.4 that could have resulted in the expected error is not executed.

From the result of [pr38](https://w3c.github.io/json-ld-api/tests/expand/pr38-in.jsonld) in the playground, it seems that steps 13.3 and 13.4 are reversed (it first checks whether it can expand to an IRI and then only ignore it if it was from a string that had the form of a keyword). In pr39, there is a vocabulary mapping, so the expansion of the keyword form is a valid IRI, hence the absence of error.

**Comment by gkellogg** [comment]
Note that the Playground isn't always up-to-date, although it should be fairly soon.

But, in this case, you are correct; my code was doing the check after generating an IRI, which was invalid. By checking it before, a different result is expected.

I'll update the affected test cases in a new PR.

**Comment by gkellogg** [comment]
@roptat this is fixed in #389, please indicate if this addresses your issue.

cc/ @kasei @niklasl

**Comment by roptat** [comment]
I believe pr38 is also affected, and unless I'm mistaken, your PR doesn't include any change to that. The invalid IRI was due to the fact that the check for the validity of the IRI was done before ignoring the keyword-like value. If you reverse the order, then the value is ignored before it can be checked, so no error should be raised.

**Comment by gkellogg** [comment]
Indeed, should be fixed now.

**Comment by roptat** [comment]
I think it's good now, although I don't have the rdf implementation yet, so I can't speak about that part of your PR :)
