### ISSUE TITLE
keyword redefinition and protection

### ISSUE THREAD

**Issue by roptat** [w3c/json-ld-api#387]
When creating a term definition for `@type`, the document says at step 4 "value MUST be a map with only the entry `@container` and value `@set` and optional entry `@protected`", which I interpret as "it must contain an `@container` whose value is `@set` and may also have `@protected` but nothing else". However, looking at test [pr32](https://w3c.github.io/json-ld-api/tests/expand/pr32-in.jsonld), it seems that the following is not a keyword redefinition:

```json
{
  "@type": {"@protected": true}
}
```

After changing my implementation to allow the value to not contain any `@container`, the test passes (I get a protected term redefinition as expected, from step 27), without any new failure.

**Comment by gkellogg** [comment]
The next should say that it MUST be a map with either or both of the members `@container` with the value `@set` and `@protected`.

**Comment by roptat** [comment]
so it can't be an empty map?

**Comment by gkellogg** [comment]
@roptat this is fixed in #390, please let us know if this satisfies your issue.

cc/ @kasei

**Comment by roptat** [comment]
I think it does, thank you!

**Comment by roptat** [comment]
actually if it's not too late, it would be nice to have a test case for the empty map, as a corner case

**Comment by gkellogg** [comment]
Generally, we encourage new tests to test corner-cases. I'll cook something up.
