### ISSUE TITLE
base IRI in compaction

### ISSUE THREAD

**Issue by roptat** [w3c/json-ld-api#396]
Hi, in the `compact` function of the API, it is said in step 7 to set base IRI to some value, but it does not seem to be used afterwards. It is not clear from the description how this base IRI is used. From tests (r001 for instance), it seems that it should be used during IRI compaction, but I'm not sure how or where?

**Comment by gkellogg** [comment]
If you're looking at the [Editor's Draft](https://w3c.github.io/json-ld-api/#dom-jsonldprocessor-compact), step 7 says to initialize _active context_ using _context base_ as _base URL_, which is an argument to the [Context Processing algorithm](https://w3c.github.io/json-ld-api/#algorithm). There, is is used when fetching remote contexts, which may be relative URLs.

In step 9, we do initialize _base IRI_, but this is not a local variable or an argument, but it should probably be the [base IRI](https://w3c.github.io/json-ld-api/#dfn-context-base-iri) field within the _active context_.

I can include a fix for this in #395.

**Comment by roptat** [comment]
great, thanks!
