### ISSUE TITLE
html extraction when empty

### ISSUE THREAD

**Issue by roptat** [w3c/json-ld-api#398]
Test e006 in https://w3c.github.io/json-ld-api/tests/html-manifest.jsonld is a positive evaluation, but according to the process HTML algorithm, it should fail. At step 4, `source` is still not defined, as no script element can be found that match previous criteria. Since extract all scripts is not set here, we try to find the first JsonLD script element, which doesn't exist. According to step 4, "If no such element is found [...]  the promise is rejected with a JsonLdError whose code is set to loading document failed and processing is terminated". So the test should either set extract all scripts to true or be a negative evaluation test.

**Comment by gkellogg** [comment]
Should be fixed in #404.

**Comment by roptat** [comment]
thank you, I think it solves this issue.
