### ISSUE TITLE
html test fragment identifier

### ISSUE THREAD

**Issue by roptat** [w3c/json-ld-api#399]
Test e011 tests the behavior of the algorithm when the specified fragment does not exist. It expects an `invalid script element` error, but according to step 2, when no element with the identifier is found, a `loading remote document failed` error is supposed to happen.

**Comment by gkellogg** [comment]
@roptat there were a couple of other tests that should have been "loading document failed" as well.

Let us know if PR #400 is satisfactory.

**Comment by roptat** [comment]
I think that solves it, thank you!
