### ISSUE TITLE
compaction test pr02

### ISSUE THREAD

**Issue by roptat** [w3c/json-ld-api#401]
In test pr02 in the compaction test suite, the expected result is a protected term redefinition error. However, the first definition is protected, and its IRI is resolved against the base. The second definition has an explicit id which is the same as the one resolved from the base. Because of step 27.1, since the two definitions are the same (except for the protected flag), there is no error. I believe the test should be a positive evaluation, or the second id should be modified to make the test fail as expected.

**Comment by gkellogg** [comment]
Should be fixed in #404.

**Comment by roptat** [comment]
thank you, I think it solves this issue.
