### ISSUE TITLE
compaction test pr03

### ISSUE THREAD

**Issue by roptat** [w3c/json-ld-api#402]
compaction test pr03 is expected to fail with a protected term redefinition. However, when processing `Type`, the context creation algorithm is called from step 21.3 which specifies "If any error is detected, an invalid scoped context error has been detected and processing is aborted.". Therefore, I believe the test should expect an invalid scoped context error instead.

**Comment by roptat** [comment]
unless I'm missing something, I believe pr04 should fail too, for the same reason.

**Comment by gkellogg** [comment]
Step 21.3 of the Compaction Algorithm expands the scoped context with _override protected_ set to `true`, so this step wouldn't catch the error. It would be when applying the context in Compaction that the error would be detected.

So, I think the existing behavior is okay. Same for pr04.

**Comment by roptat** [comment]
Indeed, I forgot to pass the flag from the context processing algorithm. This means that there was no test for that in the expand test suite.

**Comment by gkellogg** [comment]
Typically we try to find these issues in expansion tests, but there may have been something that made it difficult in this case. In any case, we show coverage.
