### ISSUE TITLE
pi* compaction tests

### ISSUE THREAD

**Issue by roptat** [w3c/json-ld-api#406]
In compaction, step 12.8.9.6 says to use container key, but using index key instead seems to solve a first issue, where the container key is not defined in the object. (so the result is something like `{"author": {"@none": {"@id": "...", "prop": "..."}}}` instead of `{"author": {"prop": {"@id": "..."}}}`).

Replacing container key with index key in that step in my implementation made tests pi* pass, except for pi06, in which my implementation tries to use `{"@id": "guest"}` and such as a key, instead of "@none". I believe some instructions are missing for the case where the index-key is associated with a value that is not a string.

**Comment by gkellogg** [comment]
Actually, it looks like _container key_ should be re-initialized by compacting _index key_ with `vocab: true` using the active context.

**Comment by gkellogg** [comment]
@roptat addressed in PR #414. Please let us know if this satisfies your issue.

**Comment by roptat** [comment]
yep, it looks good, thank you!
