### ISSUE TITLE
Only @type value from last named graph retained in framing result

### ISSUE THREAD

**Issue by fkleedorfer** [w3c/json-ld-api#407]
There seems to be a flaw in the specification of the [Merge Node Maps](https://w3c.github.io/json-ld-api/#merge-node-maps) algorithm in JSON-LD11-API. Step 2.2.1 adds property and values to merged node for keywords, overwriting `@type` values picked up from previously processed graphs with the value found in the current one. It should probably be run only where property is a keyword other than `@type`, and allow the otherwise clause in 2.2.2 to merge values.
(paraphrasing @gkellogg's [comment](https://github.com/digitalbazaar/jsonld.js/issues/378#issuecomment-595915036) on this [issue ](https://github.com/digitalbazaar/jsonld.js/issues/378) originally posted in the digitalbazaar/jsonld.js repository)

Test case:

The same resource is present in multiple named graphs. It has one or more `@type` entries in each graph, all different. When framing (matching on `@id`), only the `@type` values from the last graph are present in the result. 

The test case below shows that for normal properties, all values are picked up (see `ex:multipleValues`). When using `rdf:type` instead of `@type`, all values are picked up - this could be used as a workaround until this issue is fixed.

Tested on [json-ld playground](https://json-ld.org/playground/#startTab=tab-framed&json-ld=%7B%22%40context%22%3A%7B%22ex%22%3A%22http%3A%2F%2Fexample.com%23%22%2C%22rdf%22%3A%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%22%7D%2C%22%40graph%22%3A%5B%7B%22%40graph%22%3A%5B%7B%22%40id%22%3A%22ex%3Aentity1%22%2C%22%40type%22%3A%5B%22ex%3AType1%22%2C%22ex%3AType2%22%5D%2C%22ex%3Atitle%22%3A%22some%20title%22%2C%22ex%3AmultipleValues%22%3A%22ex%3AOne%22%7D%5D%2C%22%40id%22%3A%22ex%3Agraph1%22%7D%2C%7B%22%40graph%22%3A%5B%7B%22%40id%22%3A%22ex%3Aentity1%22%2C%22%40type%22%3A%22ex%3AType3%22%2C%22ex%3Atags%22%3A%22tag1%20tag2%22%2C%22ex%3AmultipleValues%22%3A%5B%22ex%3ATwo%22%2C%22ex%3AThree%22%5D%7D%5D%2C%22%40id%22%3A%22ex%3Agraph2%22%7D%5D%7D&frame=%7B%22%40context%22%3A%7B%22ex%22%3A%22http%3A%2F%2Fexample.com%23%22%2C%22rdf%22%3A%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%22%7D%2C%22%40id%22%3A%22ex%3Aentity1%22%7D) (links to this testcase)

Input:
```
{
    "@context": {
        "ex": "http://example.com#",
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    },
    "@graph": [
        {
            "@graph": [
                {
                    "@id": "ex:entity1",
                    "@type": [
                        "ex:Type1",
                        "ex:Type2"
                    ],
                    "ex:title": "some title",
                    "ex:multipleValues": "ex:One"
                }
            ],
            "@id": "ex:graph1"
        },
        {
            "@graph": [
                {
                    "@id": "ex:entity1",
                    "@type": "ex:Type3",
                    "ex:tags": "tag1 tag2",
                    "ex:multipleValues": [
                        "ex:Two",
                        "ex:Three"
                    ]
                }
            ],
            "@id": "ex:graph2"
        }
    ]
}
```
frame:
``` 
{
    "@context": {
        "ex": "http://example.com#",
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    },
    "@id": "ex:entity1"
}
```
output:
```
{
    "@context": {
        "ex": "http://example.com#",
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    },
    "@graph": [
        {
            "@id": "ex:entity1",
            "@type": "ex:Type3",
            "ex:multipleValues": [
                "ex:One",
                "ex:Two",
                "ex:Three"
            ],
            "ex:tags": "tag1 tag2",
            "ex:title": "some title"
        }
    ]
}
```
expected output: (all three values for `@type`, not just `ex:Type3`)
```
{
    "@context": {
        "ex": "http://example.com#",
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    },
    "@graph": [
        {
            "@id": "ex:entity1",
            "@type": [
                "ex:Type1",
                "ex:Type2",
                "ex:Type3"
            ],
            "ex:multipleValues": [
                "ex:One",
                "ex:Two",
                "ex:Three"
            ],
            "ex:tags": "tag1 tag2",
            "ex:title": "some title"
        }
    ]
}
```

**Comment by gkellogg** [comment]
@fkleedorfer Should be fixed in PR #413 with test in w3c/json-ld-framing#103. Please let us know if this solves your issue.

**Comment by davidlehn** [comment]
jsonld.js and playground updated with the fix.

**Comment by fkleedorfer** [comment]
@gkellogg works as expected now, thanks for fixing this so quickly!
