### ISSUE TITLE
Vocab scope in toRdf-tc010

### ISSUE THREAD

**Issue by rubensworks** [w3c/json-ld-api#408]
Test [toRdf-tc010](https://w3c.github.io/json-ld-api/tests/toRdf-manifest#tc010) defines the following input:
```json
{
  "@context": {
    "@vocab": "http://example/",
    "B": {"@context": {"c": "http://example.org/c"}}
  },
  "a": {
    "@context": {"@vocab": "http://example.com/"},
    "@type": "B",
    "a": "A in example.com",
    "c": "C in example.org"
  },
  "c": "C in example"
}
```

And it expects the following output:
```
_:b0 <http://example/a> _:b1 .
_:b0 <http://example/c> "C in example" .
_:b1 <http://example.org/c> "C in example.org" .
_:b1 <http://example.com/a> "A in example.com" .
_:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example/B> .
```

It is however unclear to me why this last triple has `http://example/B` as object, instead of `http://example.com/B`.

In the [syntax document](https://w3c.github.io/json-ld-syntax/#example-47-expansion-using-embedded-and-scoped-contexts), it is mentioned that _"A property-scoped context is processed first, followed by any embedded context, followed lastly by the type-scoped contexts, in the appropriate order."_

This would be my understanding of this:
When handling the node value of `"a"`, this would mean that the `@context` value would be handled first, and set `@vocab` of this node to `http://example.com/`. Next, the type-scoped context would be processed, inheriting this vocab (?). So `B` would be expanded based on vocab set to`http://example.com/`.

-----

When removing the type-scoped context definition I do get the output I would expect (with `http://example.com/B`) with the distiller and the JSON-LD playground:
```json
{
  "@context": {
    "@vocab": "http://example/"
  },
  "a": {
    "@context": {"@vocab": "http://example.com/"},
    "@type": "B",
    "a": "A in example.com",
    "c": "C in example.org"
  },
  "c": "C in example"
}
``` 
Output:
```
_:b0 <http://example/a> _:b1 .
_:b0 <http://example/c> "C in example" .
_:b1 <http://example.com/a> "A in example.com" .
_:b1 <http://example.com/c> "C in example.org" .
_:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/B> .
```

Is this inconsistency intentional?

**Comment by gkellogg** [comment]
> Test [toRdf-tc010](https://w3c.github.io/json-ld-api/tests/toRdf-manifest#tc010) defines the following input:
> ...
> 
> And it expects the following output:
> 
> ```
> _:b0 <http://example/a> _:b1 .
> _:b0 <http://example/c> "C in example" .
> _:b1 <http://example.org/c> "C in example.org" .
> _:b1 <http://example.com/a> "A in example.com" .
> _:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example/B> .
> ```
> 
> It is however unclear to me why this last triple has `http://example/B` as object, instead of `http://example.com/B`.

The top-most context establishes a term "B", which is expanded to "http://example/B". As nothing removes this term, it remains in-scope after resetting `@vocab` to "http://example.com/".

> In the [syntax document](https://w3c.github.io/json-ld-syntax/#example-47-expansion-using-embedded-and-scoped-contexts), it is mentioned that _"A property-scoped context is processed first, followed by any embedded context, followed lastly by the type-scoped contexts, in the appropriate order."_
> 
> This would be my understanding of this:
> When handling the node value of `"a"`, this would mean that the `@context` value would be handled first, and set `@vocab` of this node to `http://example.com/`. Next, the type-scoped context would be processed, inheriting this vocab (?). So `B` would be expanded based on vocab set to`http://example.com/`.

If "B" weren't a term already in the active context, then yes, it would expand relative to the new vocabulary, but it is already a term in the active context with an expansion determined when it was introduced. But, of course, if it weren't introduced, there would be no type-scoped context to introduce.

> When removing the type-scoped context definition I do get the output I would expect (with `http://example.com/B`) with the distiller and the JSON-LD playground:
> 
> ```json
> {
>   "@context": {
>     "@vocab": "http://example/"
>   },
>   "a": {
>     "@context": {"@vocab": "http://example.com/"},
>     "@type": "B",
>     "a": "A in example.com",
>     "c": "C in example.org"
>   },
>   "c": "C in example"
> }
> ```
> 
> Output:
> 
> ```
> _:b0 <http://example/a> _:b1 .
> _:b0 <http://example/c> "C in example" .
> _:b1 <http://example.com/a> "A in example.com" .
> _:b1 <http://example.com/c> "C in example.org" .
> _:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/B> .
> ```
> 
> Is this inconsistency intentional?

Not inconsistent, the term "B" is in scope, so lives to be expanded and introduce a type-scoped context.

**Comment by rubensworks** [comment]
> The top-most context establishes a term "B", which is expanded to "http://example/B". As nothing removes this term, it remains in-scope after resetting @vocab to "http://example.com/".

Thanks for clarifying this, I wasn't aware of this feature yet.

Would it make sense to add dedicated tests for this? Because I haven't come across this feature yet in any other test.

**Comment by gkellogg** [comment]
I think it’s always worth adding minimal tests that can expose issues. Please go ahead.
