### ISSUE TITLE
Incorrect description of "invalid container mapping" error code

### ISSUE THREAD

**Issue by rubensworks** [w3c/json-ld-api#424]
The error code of ["invalid container mapping"](https://w3c.github.io/json-ld-api/#dom-jsonlderrorcode-invalid-container-mapping) contains the following description:

> An @container entry was encountered whose value was not one of the following strings: @list, @set, or @index.

This seems to be not the case anymore in 1.1.

**Comment by gkellogg** [comment]
Yes, this needs to be expanded.
