### ISSUE TITLE
Incorrect test toRdf ter21

### ISSUE THREAD

**Issue by rubensworks** [w3c/json-ld-api#425]
[toRdf test ter21](https://w3c.github.io/json-ld-api/tests/toRdf-manifest#ter21) contains the following:

```json
 {
  "@context": {
    "term": {"@id": "http://example/term", "@container": "@id"}
  },
  "@id": "http://example/test#example"
}
```

According to the test, an `invalid container mapping` error is expected.
As far as I understand the spec, this is incorrect.

Both the playground and the distiller accept this as input without any errors.

Perhaps this test should be marked as 1.0-only?

**Comment by gkellogg** [comment]
It’s an error when the processingMode is json-ld-1.0,which needs to be set through an API option. The playground doesn’t have a UI to do this, although I believe the distiller does.

In 1.0 mode, `@container` can only be one of `@index, @language, @list` or `@set`.

**Comment by rubensworks** [comment]
My apologies, I was looking at the wrong test.
The `json-ld-1.0` `processingMode` option was properly set in the test manifest.
