### ISSUE TITLE
Missing tests with expected error code

### ISSUE THREAD

**Issue by rubensworks** [w3c/json-ld-api#432]
For reference, tests for the following error codes are missing:

* ~~`IRI confused with prefix`: Present for compact, but not for fromRdf.~~
* `invalid @prefix value`: Missing for both expand and toRdf.
* `context overflow`: Missing for both expand and toRdf.

(I only check the compact, expand, toRdf and fromRdf manifests)

**Comment by gkellogg** [comment]
Some of these are tested in other manifests:

* `IRI confused with prefix`: [compact-manifest#te002](https://w3c.github.io/json-ld-api/tests/compact-manifest.html#te002). This really only happens on compaction.
* `invalid @prefix value`:  [compact-manifest#tep08](https://w3c.github.io/json-ld-api/tests/compact-manifest.html#tep08). There could be an expand/toRdf test for this.
* `context overflow`: no test for this; it's challenging, as there is no defined max context stack.

**Comment by rubensworks** [comment]
> IRI confused with prefix: compact-manifest#te002. This really only happens on compaction.

Indeed, never mind, I didn't look closely enough at the reason for the error.

> context overflow: no test for this; it's challenging, as there is no defined max context stack.

The max context stack size could become a processor option, so that it can be set to a (low) level in the tests. But that might not be feasible anymore at this stage of the WG.
