### ISSUE TITLE
compaction implementation difficulties

### ISSUE THREAD

**Issue by roptat** [w3c/json-ld-api#434]
Hi,

as I'm trying to implement the compaction algorithm, I'm still having some troubles related to tests, and mostly with container mappings. Here is an example, with test t0029. The context is the following:

```json
{
  "@context": {
    "author": {"@id": "http://example.com/vocab/author", "@container": "@index" }
  }
}
```

and the inverse context (from my implementation) is:

```json
{
  "http://example.com/vocab/author": {
    "@index": {
      "@language": {"@none": "author"},
      "@type": {"@none": "author"},
      "@any": {"@none": "author"}
    }
  }
}
```

The data to compact is an array of two elements of this form:

```
{ "http://example.com/vocab/author":
  [ {"@index": "something", "@id": "somethingelse"}, … ]}
```

For the author key, I have to execute step 12.8 of the compaction algorithm, that uses the iri compaction algorithm to compact "http://example.com/vocab/author". Expanded item is the first element of the array above: `{"@index": "something", "@id": "somethingelse"}`. We try to iri compact `http://example.com/vocab/author` with that element.

In the iri compaction algorithm, vocab is true and var is an entry in inverse context, so we execute step 4. Some of the steps add values to containers. Initially, it is empty:

- 4.5: value contains `@index`, but it is not a map, so nothing to do
- 4.6: reverse is false, so nothing to do
- 4.7: value is not a list object, so skip
- 4.8: value is not a graph object, so skip
- 4.9: none of the above cases matched, so we execute this.
  - 4.9.1: value is not a value object, so skip
  - 4.9.2: we add `@id`, `@id@set`, `@type`, and `@set@type` to containers
  - 4.9.3: we add `@set` to containers
- 4.10: we add `@none` to containers
- 4.11: processing mode is indeed 1.1, but value is a map and does contain an `@index` key, so skip
- 4.12: processing mode is indeed 1.1, but value is a map that doesn't only contain `@value`, so skip

In the end, containers contains `[@id, @id@set, @type, @set@type, @set, @none]`. None of them are the expected `@index` which is the only one that can give the correct compaction.

**Comment by gkellogg** [comment]
> Hi,
> 
> as I'm trying to implement the compaction algorithm, I'm still having some troubles related to tests, and mostly with container mappings. Here is an example, with test t0029. The context is the following:
> 
> ```json
> {
>   "@context": {
>     "author": {"@id": "http://example.com/vocab/author", "@container": "@index" }
>   }
> }
> ```
> 
> and the inverse context (from my implementation) is:
> 
> ```json
> {
>   "http://example.com/vocab/author": {
>     "@index": {
>       "@language": {"@none": "author"},
>       "@type": {"@none": "author"},
>       "@any": {"@none": "author"}
>     }
>   }
> }
> ```

This looks correct.

> The data to compact is an array of two elements of this form:
> 
> ```
> { "http://example.com/vocab/author":
>   [ {"@index": "something", "@id": "somethingelse"}, … ]}
> ```
> 
> For the author key, I have to execute step 12.8 of the compaction algorithm, that uses the iri compaction algorithm to compact "http://example.com/vocab/author". Expanded item is the first element of the array above: `{"@index": "something", "@id": "somethingelse"}`. We try to iri compact `http://example.com/vocab/author` with that element.
> 
> In the iri compaction algorithm, vocab is true and var is an entry in inverse context, so we execute step 4. Some of the steps add values to containers. Initially, it is empty:
> 
> * 4.5: value contains `@index`, but it is not a map, so nothing to do
> * 4.6: reverse is false, so nothing to do
> * 4.7: value is not a list object, so skip
> * 4.8: value is not a graph object, so skip
> * 4.9: none of the above cases matched, so we execute this.
>   
>   * 4.9.1: value is not a value object, so skip
>   * 4.9.2: we add `@id`, `@id@set`, `@type`, and `@set@type` to containers
>   * 4.9.3: we add `@set` to containers
> * 4.10: we add `@none` to containers
> * 4.11: processing mode is indeed 1.1, but value is a map and does contain an `@index` key, so skip
> * 4.12: processing mode is indeed 1.1, but value is a map that doesn't only contain `@value`, so skip
> 
> In the end, containers contains `[@id, @id@set, @type, @set@type, @set, @none]`. None of them are the expected `@index` which is the only one that can give the correct compaction.

Step 4.5 seems incorrect: it shouldn't matter that the value of `@index` is a map. My implementation doesn't check for this, neither do jsonld.js nor pyld. I'm not sure why that language was added.

Check it out, and if that solves your problem, I'll revise the step.

**Comment by roptat** [comment]
Thank you! removing that test brings me down from 62 failed tests to 51. In particular, test 0029 passes now, thank you :)

**Comment by gkellogg** [comment]
That's great; these term selection things can be the hardest!

We'll be freezing the test suite next week in prep for an conformance report to be issued a couple of weeks later. It would be great to have an implementation report for your processor.

Let us (me) know any other issues you encounter.

**Comment by roptat** [comment]
what does an implementation report look like? What should I provide?

**Comment by gkellogg** [comment]
This is what the report will look like: https://w3c.github.io/json-ld-api/reports/. There's information there on the format, which uses the EARL vocabulary. There are also some individual implementation reports in Turtle you can see referenced.

The `doap:revision` is wrong, which I'll update. It should be more like the following:

```turtle
<https://rubygems.org/gems/json-ld> a doap:Project;
   dc:creator <https://greggkellogg.net/foaf#me>;
   doap:description "RDF.rb extension for parsing/serializing JSON-LD data."@en;
   doap:developer <https://greggkellogg.net/foaf#me>;
   doap:name "JSON::LD"^^xsd:string;
   doap:platform "Ruby"^^xsd:string;
   doap:shortdesc "JSON-LD support for RDF.rb."@en;
   doap:release [
    doap:name "json-ld-3.1.1";
    doap:revision "3.1.1";
    doap:created "2020-02-19"^^xsd:date;
  ] .
```

But, that's not critical.

**Comment by gkellogg** [comment]
Updated in #440, see if that satisfies the issue.

**Comment by roptat** [comment]
it does, thank you!
