### ISSUE TITLE
graph compaction issues

### ISSUE THREAD

**Issue by roptat** [w3c/json-ld-api#436]
I'm still having issues with compaction. This time, compacting graphs is the problem. I take 0077 as an example. Here, I need to compact `{"input": {"@graph": [{"@value": "x"}]}}`. where `input` has `@graph` in its container mapping. The expected result is `{"input": {"@value": "x"}}`, but I can't remove the `@graph` in my implementation.

When running step 12.8.6, I recursively call the compaction algorithm on `{"@graph": [{"@value": "x"}]}` with `input` as the active property. This recursive call returns the `@graph` object, not compacted.

Note that here the specification says "[passing] expanded item for element if it does not contain the entry `@list` and is not a graph object containing `@list`, otherwise pass the value of the entry for element.".  This is confusing (that last part sounded like pass the value associated with element). Reversing the sentence might make it more readable, like so: "If expanded item does not contain the entry `@list` and is not a graph object containing `@list`, pass expanded item for element, otherwise pass the value of the `@list` entry for element."

Continuing execution, I arrive at step 18.8.8.3 because the expanded item is a graph object, and container only includes `@graph`. There I simply add compacted item to result, so I have `@graph` in the result.

I think there are two points where that could have gone wrong: either step 12.8.6 where I should actually have passed only the content of the graph object, or step 12.8.8 where I should have set the result to the content of the graph object, instead of the graph object itself.

**Comment by gkellogg** [comment]
> I'm still having issues with compaction. This time, compacting graphs is the problem. I take 0077 as an example. Here, I need to compact `{"input": {"@graph": [{"@value": "x"}]}}`. where `input` has `@graph` in its container mapping. The expected result is `{"input": {"@value": "x"}}`, but I can't remove the `@graph` in my implementation.
> 
> When running step 12.8.6, I recursively call the compaction algorithm on `{"@graph": [{"@value": "x"}]}` with `input` as the active property. This recursive call returns the `@graph` object, not compacted.

This step should return `{"value":"x"}`.

The bit about "is not a graph object containing `@list`" looks wrong, it should just be "is not a graph object". The idea is to compact _expanded item_, or the value of its `@list` or `@graph` elements.

> Note that here the specification says "[passing] expanded item for element if it does not contain the entry `@list` and is not a graph object containing `@list`, otherwise pass the value of the entry for element.". This is confusing (that last part sounded like pass the value associated with element). Reversing the sentence might make it more readable, like so: "If expanded item does not contain the entry `@list` and is not a graph object containing `@list`, pass expanded item for element, otherwise pass the value of the `@list` entry for element."

The structure of the sentence describes each of the input variables, and the conditional on the last does, indeed, complicated it, but I don't think we can entirely separate it out. Perhaps the following:

> **Initialize _compacted item_ to the result of using this algorithm recursively, passing _active context_,_ item active property_ for _active property_, _expanded item_ for _element_, along with the `compactArrays` and `ordered` flags. If _expanded_item_ is a _list object_ or a _graph _object_, use the value of the `@list` or `@graph` entries, respectively, for _element_ instead of _expanded _item_.**

See if that addresses this issue.

**Comment by roptat** [comment]
this sounds a lot better

**Comment by roptat** [comment]
with this change, 28 tests that used to fail now pass, 5 still fail and 1 more test, 0016, used to pass but now fail.

**Comment by gkellogg** [comment]
Updated in #440, see if that satisfies the issue.

**Comment by roptat** [comment]
I think this PR doesn't have a fix for this issue (even though the description says it does)

**Comment by gkellogg** [comment]
See https://github.com/w3c/json-ld-api/pull/440/files#r399866226.

**Comment by roptat** [comment]
oh, indeed! that fixes this issue, thanks again :)
