### ISSUE TITLE
compaction: remaining singleton values

### ISSUE THREAD

**Issue by roptat** [w3c/json-ld-api#438]
In steps 12.8.9.6 and 12.8.9.8, we examine the values associated with a key. There can be one or more values. The first value is used, and when there are remaining values, the specification asks to set a value is compacted item to those remaining values.

However, it is not clear what to do when there is only one remaining value. As I understood it, the specification says to use an array even for a single value. However, in test m004, there are two types for each object. The remaining value is therefore an array with one value, but the expected output is a single value, not an array.

The specification should say what to do when there is only one remaining value. For 12.8.9.8, I followed test m004 and used the value instead of the array in my implementation, and I think the specification should say so too. I'm not sure about 12.8.9.6.

**Comment by gkellogg** [comment]
Perhaps it would be more clear if we used the (revised) _add\_value_ macro. Generally, unless `asArray` is `true` or `@container` includes `@set`, singleton items are not represented using an array.

**Comment by gkellogg** [comment]
Updated in #440, see if that satisfies the issue.

**Comment by roptat** [comment]
it does, thank you!
