### ISSUE TITLE
compaction: type-scoped context

### ISSUE THREAD

**Issue by roptat** [w3c/json-ld-api#439]
In test [c009](https://w3c.github.io/json-ld-api/tests/compact/c009-in.jsonld), we test that the type-scoped context is not propagated to nested nodes. However, I think the specification doesn't prevent it. When we examine the object, we execute step 11 which updates active context. This active context is passed to nested nodes. In the nested nodes, the active context contains a definition for baz whose type is vocab, leading to a different IRI in the result.

I believe that passing false for the propagate flag when calling the context processing algorithm in step 11 is enough, as the original context will be saved in the previous context of the new active context. When recursing on the compaction algorithm, step 5 will ensure that we use the original context instead of the new one in nested nodes.

This change helped me pass 8 tests (4 of which had additional issues that I now fixed) and didn't create any new test failure.

**Comment by gkellogg** [comment]
Yes, should use `propagate: false`.

**Comment by gkellogg** [comment]
Updated in #440, see if that satisfies the issue.

**Comment by roptat** [comment]
it does, thank you!
