### ISSUE TITLE
no jld:PositiveSyntaxTest instruction

### ISSUE THREAD

**Issue by roptat** [w3c/json-ld-api#449]
I'm now trying to implement the toRdf and fromRdf algorithms, and I'm facing an issue with the test suite: some toRdf tests have type jld:PositiveSyntaxTest, but it doesn't seem to be described, so I'm not sure what I should do with them?

**Comment by gkellogg** [comment]
Here's the Turtle version of the vocabulary definition (from [tests/vocab.html](https://w3c.github.io/json-ld-api/tests/vocab.html)) for `PositiveSyntaxTest`:

```ttl
:PositiveSyntaxTest a rdfs:Class ;
  rdfs:subClassOf :Test ;
  rdfs:label "Positive Syntax Test" ;
  rdfs:comment """
    A type of test specifically for syntax testing.
    Syntax tests are not required to have an associated result, only an action.
  """ .
```

Basically, just run the operation and either match on the expected exception, or don't expect an exception.

**Comment by roptat** [comment]
Thank you! A short explanation in the test index would have been great, but that's what I implemented without further information, so ok :)

**Comment by gkellogg** [comment]
Updated in #464. Please let us know if this satisfies the issue.

**Comment by roptat** [comment]
Looks good, thank you!
