### ISSUE TITLE
Unused argument in Create Term Definition

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#451]
The `validate scoped context` argument to [Create Term Definition](https://w3c.github.io/json-ld-api/#create-term-definition) is never used.

**Comment by gkellogg** [comment]
`validate scoped context` should be passed as `true` when calling the Context Processing Algorithm from the Create Term Definition Algorithm when processing `@context`.

**Comment by kasei** [comment]
> `validate scoped context` should be passed as `true` when calling the Context Processing Algorithm from the Create Term Definition Algorithm when processing `@context`.

Is there a test that depends on this? I use `false` as currently written in the document, and pass all tests, so I'm worried that I've either done something wrong, or the test suite doesn't cover this.

**Comment by kasei** [comment]
And either way, if the value being passed is constant, why does Create Term Definition even need this as an argument (since it is never used)?

**Comment by gkellogg** [comment]
Updated in #464. Please let us know if this satisfies the issue.

**Comment by helins** [comment]
I stumbled accros the very same problem while implementing Create Term Definition and I don't think this is issue has been solved:

a) The change pertaining to Context Processing passing `validate scoped context` to Create Term Definition is not part of the lastest version, what happened?

b) I assume that Create Term Definition should pass the `validate scoped context` back to Context Processing (or default to `true`, step 21.3 of Create Term Definition mentions `false`).

**Comment by gkellogg** [comment]
The `validate scoped context` option is, in fact used, in step 21.3 of the Create Term Definition algorithm. This is the case when we see a scoped context within a term definition, and we want to process that context without validating it.


> 21.3 Invoke the [Context Processing algorithm](https://w3c.github.io/json-ld-api/#context-processing-algorithm) using the active context, context as local context, base URL, `true` for <var>override protected</var>, a copy of remote contexts, and **`false` for <var>validate scoped context</var>**. If any error is detected, an [invalid scoped context](https://w3c.github.io/json-ld-api/#dom-jsonlderrorcode-invalid-scoped-context) error has been detected and processing is aborted.

**Comment by helins** [comment]
Thanks @gkellogg, so you confirm that `21.3` should indeed pass `false` as mentioned in the specs. Then, since it is the only mention of `validate scoped context` in `Create Term Definition, am I correct in assuming that the original post is correct and `Create Term Definition` does not need `validate scoped context` as an optional input?

```
4.2.2. The algorithm has four required and five optional inputs [...] and validate scoped context defaulting to true, which is used to limit recursion...
```

**Comment by gkellogg** [comment]
In both Create Term Definition and the Context Processing algorithms, the parameter has a default value of `true`, so is not typically going to be specified unless it's somehow different. in 12.3 of CTD it's set to `false`, and in 5.2.6 of CP the input value is passed recursively. The reason the CTD algorithm passes it explicitly as false in this context is to avoid validation. It may also be passed as false if that is the value that CTD was called with, which could happen for a couple of reasons.
