### ISSUE TITLE
Implementation report shows multiple versions for some implementations

### ISSUE THREAD

**Issue by rubensworks** [w3c/json-ld-api#459]
It looks like the implementation report shows multiple versions for some implementations.
For example,  jsonld-streaming-parser shows `["2.0.0", "1.1.0", "1.3.0"]`.

I assume this is because jsonld-streaming-parser, jsonld-streaming-serializer, and rdf-parse all use the blank node `_:b_release`as value for `doap:release`, and the implementation report tooling directly concatenating all raw reports, instead of considering all blank node identifiers document-local. But @gkellogg may know better why this is happening.

**Comment by gkellogg** [comment]
I noticed that, but it shouldn't be concatenating these together from different reports, unless they use the same BNode, but they're queried separately, so I don't see how that would be the case. I'll look to see what the software's doing more closely.

**Comment by gkellogg** [comment]
Yes, the code ended up reusing the blank node between the three different implementations. They were actually three unique blank nodes, but all had the same label, so when serializing back to JSON-LD, those labels were reused. I remapped within the tool, so shouldn't be a problem going forward.
