### ISSUE TITLE
serialize RDF description

### ISSUE THREAD

**Issue by roptat** [w3c/json-ld-api#460]
§ 8.4.2 (serialize RDF algorithm) says the algorithm takes five optional flags, and cites only 4, ordered, rdfDirection, useNativeTypes and useRdfTypes. Also, can rdfDirection be called a flag? It's not really a boolean.

**Comment by gkellogg** [comment]
Updated in #464. Please let us know if this satisfies the issue.

**Comment by roptat** [comment]
looks good, thank you!
