### ISSUE TITLE
RDF to object with native type

### ISSUE THREAD

**Issue by roptat** [w3c/json-ld-api#461]
In RDF to object, step 2.4 is executed because useNativeType is true. When the datatype is xsd:decimal as in test 0018, none of the steps in 2.4 can be executed. Test 0018 seems to expect something more, either "Otherwise, continue from step 2.5" or "Otherwise, set to the datatype IRI of value, unless it equals xsd:string which is ignored" (as in step 2.8). Both seem to satisfy the test, so I'm not sure which one is intended here.

**Comment by gkellogg** [comment]
You're referring to processing of the following triple:
```ttl
<http://example.com/Subj1> <http://example.com/prop> "1.1"^^<http://www.w3.org/2001/XMLSchema#decimal> .
```
In this case, 2.4 does not apply, as the datatype does not match xsd:string, xsd:integer, xsd:double, or xsd:boolean.

Step 2.5 is specifically for JSON literals (i.e., datatype is `http://www.w3.org/1999/02/22-rdf-syntax-ns#JSON`), so does not apply.

The relevant step is 2.8, where _type_ is set to `http://www.w3.org/2001/XMLSchema#decimal` and 2.9 where `@value` is set to "1.1".

This is exactly what appears in the expected result.

Only boolean, integer or double values may be expressed natively (and string, of course). Meaning that "1"^^xsd:integer can be expressed as `1` and not `{"@value": "1", "@type": "xsd:integer"}`.

**Comment by roptat** [comment]
right, 2.4 only says "If useNativeTypes is true" so I though it would apply in any case, but I think I understand now. Thank you!
