### ISSUE TITLE
serialize RDF and compound-literal

### ISSUE THREAD

**Issue by roptat** [w3c/json-ld-api#462]
In step 6.1.6, references to "node" should be references to "cl-reference".

**Comment by gkellogg** [comment]
Thanks, I'll fix.

BTW, I hope we'll see an implementation report from you shortly. It was actually due by Friday, but we've extended a week to get more implementation reports in.

**Comment by roptat** [comment]
I managed to implement the RDF algorithms, and apart from a few issues with libraries I have reported upstream, all tests pass :) I'll send a report shortly.

**Comment by gkellogg** [comment]
Updated in #464. Please let us know if this satisfies the issue.

**Comment by roptat** [comment]
Looks good, thank you!
