### ISSUE TITLE
Implementation report issues

### ISSUE THREAD

**Issue by davidlehn** [w3c/json-ld-api#469]
- The ToC has link to "Test Definitions" which doesn't exist.  If that's gone, appendix D should be renamed to C and that ToC line removed.
- Is there a way to make the "Test Subjects" have stable links? The auto-generated "#subj_N" ones can change around as subjects are added/removed/etc.

**Comment by davidlehn** [comment]
- Descriptions are only used if they language tagged "en"?  Could that fallback to untagged data?

**Comment by gkellogg** [comment]
> * The ToC has link to "Test Definitions" which doesn't exist.  If that's gone, appendix D should be renamed to C and that ToC line removed.

It's a remnant of when we did include them; I'll fix.

> * Is there a way to make the "Test Subjects" have stable links? The auto-generated "#subj_N" ones can change around as subjects are added/removed/etc.

SMOS :) I'll take care of it.

**Comment by gkellogg** [comment]
> * Descriptions are only used if they language tagged "en"?  Could that fallback to untagged data?

Anything is possible, but as the report is in english, it makes sense that the english version of such descriptive terms be used. It could fall back, but that complicates the software, and the instructions for the DOAP/EARL format are fairly clear and shouldn't be too difficult to conform to.

**Comment by davidlehn** [comment]
> > * Descriptions are only used if they language tagged "en"?  Could that fallback to untagged data?
> 
> Anything is possible, but as the report is in english, it makes sense that the english version of such descriptive terms be used. It could fall back, but that complicates the software, and the instructions for the DOAP/EARL format are fairly clear and shouldn't be too difficult to conform to.

Ok.  I just looked into the issue after generating reports.  I'll fix pyld and jsonld.js on the next update.
