### ISSUE TITLE
'active property' is never '@list' in expansion, but spec checks for it

### ISSUE THREAD

**Issue by stephank** [w3c/json-ld-api#47]
At the time of writing, 4.2.2 of the expansion algorithm checks if 'active property' is `@list`: https://github.com/w3c/json-ld-api/blob/4c006ba6475bb488f0d0f39a0f42fe14119f5bbf/index.html#L1657-L1663

But when a `@list` property is encountered (9.4.9), the active property of its container is passed down: https://github.com/w3c/json-ld-api/blob/4c006ba6475bb488f0d0f39a0f42fe14119f5bbf/index.html#L1792-L1796

This also applies to the current 1.0 spec. The latter is needed for coercion (t0023), but an implementation following the algorithm steps now doesn't throw a 'list of lists' error (te032). It looks like some implementations now add an extra parameter to the algorithm to satisfy these tests.

**Comment by gkellogg** [comment]
Good catch, this was likely left over from code which was since removed.
