### ISSUE TITLE
Create Term Definition algorithm, possible imprecision step 5.13

### ISSUE THREAD

**Issue by timothee-haudebourg** [w3c/json-ld-api#476]
Step 5.13 of the [Context Processing Algorithm](https://www.w3.org/TR/json-ld11-api/#context-processing-algorithm), it is asked to invoke the Create Term Definition algorithm:
> passing `result` for `active context`, `context` for `local context`, `key`,
`defined`, `base URL`, and the value of the `@protected` entry from `context`,
if any, for `protected`. 

The value of input value for `override_protected` is not specified. Strictly following this, it defaults to `false` as specified in the definition of the [Create Term Definition Algorithm](https://www.w3.org/TR/json-ld11-api/#create-term-definition). This makes the [expansion test `pr40`](https://w3c.github.io/json-ld-api/tests/expand/pr40-in.jsonld) to fail.

Instead, I believe the `override_protected` value is meant to passed on from the Context Processing Algorithm to the Create Term Definition Algorithm.

**Comment by gkellogg** [comment]
This was fixed in the just-published update to the [JSON-LD11 API](https://www.w3.org/TR/2020/CR-json-ld11-api-20200417/) document. It now reads the following:

> passing `result` for `active context`, `context` for `local context`, `key`, `defined`, `base URL`, the value of the `@protected` entry from `context`, if any, for `protected`, **`override protected`, and a copy of `remote contexts`**.

**Comment by timothee-haudebourg** [comment]
Perfect, I'm closing.
