### ISSUE TITLE
Compacting IRIs associated to multi types values/nodes

### ISSUE THREAD

**Issue by timothee-haudebourg** [w3c/json-ld-api#484]
The type mapping of a term definition in a context must be a string, which means it is a single type. So in an inverse context, we have maps from single types to terms. However in an expanded document, node objects and value objects may have multiple types, stored in an array.

I'm wondering how this is handled during the compaction phase. While reading the IRI compaction algorithm, I can imagine cases where the `type/language value` variable is set to an array of types, which in turns will be part of the `prefered values` when calling the Term Selection Algorithm.

Is this intended? I guess it is not strictly incorrect since the provided algorithm is untyped, the array would just be ignored during the term selection. Or should I read the verb "append" in the step 4.17 of the IRI compaction step as "concatenate" if it an array?

**Comment by gkellogg** [comment]
When compacting, term selection only considers `@type` for value objects, not node objects. Value objects can only have a single value for `@type` (other than for frame documents). Since we don't compact frame documents, this isn't an issue.

**Comment by timothee-haudebourg** [comment]
> Value objects can only have a single value for @type

Isn't this a valid value object? (It is in my implementation and on the playground implementation)
```
{
  "@value": "value of v:term",
  "@type": ["a", "b"]
}
```

**Comment by gkellogg** [comment]
That's not a legal value object, and of course, value objects don't work at the top-level anyway.

From the [syntax document][(https://www.w3.org/TR/json-ld11/#value-objects):

> The value associated with the @type key MUST be a term, an IRI, a compact IRI, a string which can be turned into an IRI using the vocabulary mapping, `@json`, or `null`.

From the [api document expansion algorithm](https://www.w3.org/TR/json-ld11-api/#expansion-algorithm) 15.5:

> Otherwise, if the result has an `@type` entry and its value is not an IRI, an invalid typed value error has been detected and processing is aborted.

As I mentioned, there is an exception if the _framing_ flag is `true`, to allow for value objects with multiple `@type` values, or where the `@type` value is an object; this is to handle frame matching, where a frame can match on a value object having any of the associated `@type` values.

**Comment by timothee-haudebourg** [comment]
> and of course, value objects don't work at the top-level anyway.

Well, yes, I simplified it, the full example is [this one](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40id%22%3A%22foo%22%2C%22scheme%3A%2F%2Fbar%22%3A%7B%22%40value%22%3A%22value%22%2C%22%40type%22%3A%5B%22a%22%2C%22b%22%5D%7D%7D).

I wonder why I ended up accepting this (and the playground impl)... But if is not valid, that's fine then.

**Comment by gkellogg** [comment]
@davidlehn may want to look at this, as it should issue an error.

If you try it on my [distiller](http://rdf.greggkellogg.net/distiller?command=serialize&format=jsonld&output_format=jsonld), you'll see the following message:

> Failed to parse input document: invalid typed value: value of `@type` must be an IRI or `'@json'`: `{"@value"=>"value", "@type"=>["a", "b"]}`

**Comment by gkellogg** [comment]
I would also think we'd have a test case for something like this, and we might consider adding one.
