### ISSUE TITLE
Expansion of multiple type-scoped contexts

### ISSUE THREAD

**Issue by kal** [w3c/json-ld-api#498]
In the expansion algorithm step 11, when `@type` contains multiple terms each of which have a local context, step 11.2 indicates that those contexts should be chained because `active context` is updated inside the loop. 

So, if there are two terms in `@type`, processing the first results in a new context that references the initial `active context`, BUT it then updates `active context`. This means that processing the second passes the updated context (not the original outer context) in to the Context Processing Algorithm resulting in a chain of `previous context` references.

I think that the intention of the specification is that where there are multiple type-scoped contexts they are all nested inside the same outer active context, not chained together. So in step 11.2 each invocation of the Context Processing Algorithm should be passing in the same (outer) context, not incrementally updating `active context`. 

This comes up when processing expansion test c017 in the test suite. Following the algorithm I end up with the type-scoped context for `Foo` referencing the type-scoped context for `Bar` as its previous context (which in turn references the outer context as its  previous context). This fails the test and my only conclusion is that in fact the type-scoped contexts should all be referencing the outer context as their previous context.

**Comment by gkellogg** [comment]
> I think that the intention of the specification is that where there are multiple type-scoped contexts they are all nested inside the same outer active context, not chained together. So in step 11.2 each invocation of the Context Processing Algorithm should be passing in the same (outer) context, not incrementally updating `active context`.

You'll note that, as _propagate_ is passed as `false` in this case, step 3 of the [Context Processing Algorithm(https://w3c.github.io/json-ld-api/#algorithm) only updates _previous context_ in _result_ if it does not already have a _previous context_, thus the first type-scoped context processed will set it, and subsequent type-scoped context will leave it unchanged, so that when the context is eventually reverted, it has the effect of going back the the value before any type-scoped contexts were added.

**Comment by kal** [comment]
Thanks Gregg. I tracked down my implementation issue to a problem with the clone of the context object - my clone wasn't setting the previous context so although I was following that test on step 3, I was doing it with bad data. Definite case of user error! :-)
