### ISSUE TITLE
Please explain the difference between expand tests #ter02 and #ter03

### ISSUE THREAD

**Issue by danpape** [w3c/json-ld-api#506]
According to the expand-manifest description, tests #ter02 and #ter03 are for testing that "an exception is raised on expansion when processing a context referencing itself" ... with #ter02 being a direct reference and #ter03 being indirect. However, the two input files look basically the same:
https://github.com/w3c/json-ld-api/blob/master/tests/expand/er02-in.jsonld
https://github.com/w3c/json-ld-api/blob/master/tests/expand/er03-in.jsonld
and I do not see any manifest option or anything else that would make the two tests any different: how is #ter03 "indirect"?

**Comment by gkellogg** [comment]
Note that both these tests are restricted to json-ld-1.0, as the semantics have changed in 1.1. You're correct that they are the same, which was an issue the 1.0 test suite. In 1.1 there's no specific prohibition for this, as the use of scoped contexts may, indeed, cause a context to include itself recursively. A runaway is caught using a remote context counting mechanism (`context overflow`), instead.  There are no specific tests for this, as it is now a difficult to construct situation, at least for a static test suite.

**Comment by danpape** [comment]
Thanks for the explanation. I will leave them as-is in my project.
