### ISSUE TITLE
Should expand test #ter53 have specVersion of "json-ld-1.1"?

### ISSUE THREAD

**Issue by danpape** [w3c/json-ld-api#507]
Expand test #ter53 deals with invalid @prefix values, so should the test be marked with an option for "json-ld-1.1" specVersion?

**Comment by danpape** [comment]
This would also seem to apply to toRdf test #ter53.

**Comment by gkellogg** [comment]
Yes, these should be marked `"specVersion": "json-ld-1.1"`. I'll update the test suite entries.
