### ISSUE TITLE
References and side effects in compaction algorithm

### ISSUE THREAD

**Issue by timothee-haudebourg** [w3c/json-ld-api#510]
Hi,

Reading the compaction algorithm I've been confused about the use of the variables `nest result` and `map object` and how they contribute to the computation of `result`. Now I think I understand there is some hidden side effects in the algorithm. 

For instance, in the sentences:
> 12.8.2.3) Initialize `nest result` to the value of `nest term` in `result`.
> 12.8.3) Otherwise, initialize `nest result` to `result`.

Am I right to read it as "Initialize `nest result` **as a reference** to the value of `nest term` in `result`" and "otherwise, initialize `nest result` **as a reference** to `result`" so that adding entries to `nest result` latter on will modify `result`?

Same here with the `map object` variable:
> 12.8.9.1) Initialize `map object` to the value of `item active property` in `nest result`, initializing it to a new empty map, if necessary

I understand it makes no difference when writing this algorithm with high-level languages where aliasing is everywhere, but using Rust there is a big difference for a variable between being *equal to* and being a *reference to* some value. If it is not already done (maybe I missed it), it could be useful to add a note about the semantics of variable assignments in the algorithms definitions.

**Comment by pchampin** [comment]
I'd prefer @gkellogg and @dlongley to confirm this, but I believe that you assume correctly: the default semantics for assignments in the algorithm is by reference. Whenever a copy is required, it is explicitly stated (e.g. step 1 of the Value Compaction algorithm).

**Comment by gkellogg** [comment]
Yes, these are references, so that the algorithm can update the objects in place.
