### ISSUE TITLE
No roundtrip with property-based data indexing

### ISSUE THREAD

**Issue by pchampin** [w3c/json-ld-api#514]
This issue has been spotted in w3c/wot-thing-description#988. I can't yet decide if it is an implementation bug (which appears in both the playground and the Ruby distiller) or a problem in the API spec.

It is caused during compaction, when the `@index` property of a term definition using a compact IRI. Not only does it not roundtrip, but it fails with an "IRI confused with prefix" error.

Minimal example ([see in playground][1]) :
```
{
  "@context": {
    "ex": "http://example.org/ns/",
    "prop": {
      "@id": "ex:prop",
      "@container": "@index",
      "@index": "ex:name"
    }
  },
  "prop": {
    "foo": { "@id": "ex:foo"},
    "bar": { "@id": "ex:bar"}
  }
}
```
Note that expansion works fine. Replacing `"@index": "ex:name"` with `"@index": "http://example.org/ns/name"` in the *compaction* context solves the problem.

What is embarassing is that the [example from the spec][2] suffers from the same problem: it expands correctly, but fails to compact back, with the same error ([see in playground][3]).

[1]: https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%7B%22%40context%22%3A%7B%22ex%22%3A%22http%3A%2F%2Fexample.org%2Fns%2F%22%2C%22prop%22%3A%7B%22%40id%22%3A%22ex%3Aprop%22%2C%22%40container%22%3A%22%40index%22%2C%22%40index%22%3A%22ex%3Aname%22%7D%7D%2C%22prop%22%3A%7B%22foo%22%3A%7B%22%40id%22%3A%22ex%3Afoo%22%7D%2C%22bar%22%3A%7B%22%40id%22%3A%22ex%3Abar%22%7D%7D%7D&context=%7B%22%40context%22%3A%7B%22ex%22%3A%22http%3A%2F%2Fexample.org%2Fns%2F%22%2C%22prop%22%3A%7B%22%40id%22%3A%22ex%3Aprop%22%2C%22%40container%22%3A%22%40index%22%2C%22%40index%22%3A%22ex%3Aname%22%7D%7D%2C%22prop%22%3A%7B%22foo%22%3A%7B%22%40id%22%3A%22ex%3Afoo%22%7D%2C%22bar%22%3A%7B%22%40id%22%3A%22ex%3Abar%22%7D%7D%7D
[2]: https://www.w3.org/TR/json-ld11/#example-99-property-based-data-indexing
[3]: https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%7B%22%40context%22%3A%7B%22%40version%22%3A1.1%2C%22schema%22%3A%22http%3A%2F%2Fschema.org%2F%22%2C%22name%22%3A%22schema%3Aname%22%2C%22body%22%3A%22schema%3AarticleBody%22%2C%22athletes%22%3A%7B%22%40id%22%3A%22schema%3Aathlete%22%2C%22%40container%22%3A%22%40index%22%2C%22%40index%22%3A%22schema%3AjobTitle%22%7D%7D%2C%22%40id%22%3A%22http%3A%2F%2Fexample.com%2F%22%2C%22%40type%22%3A%22schema%3ASportsTeam%22%2C%22name%22%3A%22San%20Francisco%20Giants%22%2C%22athletes%22%3A%7B%22Catcher%22%3A%7B%22%40type%22%3A%22schema%3APerson%22%2C%22name%22%3A%22Buster%20Posey%22%7D%2C%22Starting%20Pitcher%22%3A%7B%22%40type%22%3A%22schema%3APerson%22%2C%22name%22%3A%22Madison%20Bumgarner%22%7D%7D%7D&context=%7B%22%40context%22%3A%7B%22%40version%22%3A1.1%2C%22schema%22%3A%22http%3A%2F%2Fschema.org%2F%22%2C%22name%22%3A%22schema%3Aname%22%2C%22body%22%3A%22schema%3AarticleBody%22%2C%22athletes%22%3A%7B%22%40id%22%3A%22schema%3Aathlete%22%2C%22%40container%22%3A%22%40index%22%2C%22%40index%22%3A%22schema%3AjobTitle%22%7D%7D%2C%22%40id%22%3A%22http%3A%2F%2Fexample.com%2F%22%2C%22%40type%22%3A%22schema%3ASportsTeam%22%2C%22name%22%3A%22San%20Francisco%20Giants%22%2C%22athletes%22%3A%7B%22Catcher%22%3A%7B%22%40type%22%3A%22schema%3APerson%22%2C%22name%22%3A%22Buster%20Posey%22%7D%2C%22Starting%20Pitcher%22%3A%7B%22%40type%22%3A%22schema%3APerson%22%2C%22name%22%3A%22Madison%20Bumgarner%22%7D%7D%7D

**Comment by RoboPhred** [comment]
I found another instance of this, happening on a `@type` key this time:
[full example](https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%7B%22%40id%22%3A%22scenes%3A%3Ascene-d6898733-95c0-4a4b-b30b-5e558aec5b48%22%2C%22%40types%22%3A%5B%5D%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Ftitle%22%3A%22New%20Scene%22%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Ftd%23hasActionAffordance%22%3A%5B%7B%22%40index%22%3A%22scenes%3A%3Aadd-property-set%22%2C%22%40type%22%3A%5B%5D%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Ftitle%22%3A%22Add%20property%22%2C%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Ftd%23hasInputSchema%22%3A%7B%22%40context%22%3A%7B%22td%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Ftd%23%22%2C%22jsonschema%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23%22%2C%22wotsec%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fsecurity%23%22%2C%22hctl%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fhypermedia%23%22%2C%22dct%22%3A%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%22%2C%22schema%22%3A%22http%3A%2F%2Fschema.org%2F%22%2C%22rdf%22%3A%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%22%2C%22%40vocab%22%3A%22https%3A%2F%2Fwww.w3.org%2F2019%2Fwot%2Fjson-schema%23%22%2C%22DataSchema%22%3A%7B%22%40id%22%3A%22jsonschema%3ADataSchema%22%7D%2C%22readOnly%22%3A%7B%22%40id%22%3A%22jsonschema%3AreadOnly%22%2C%22%40type%22%3A%22xsd%3Aboolean%22%7D%2C%22writeOnly%22%3A%7B%22%40id%22%3A%22jsonschema%3AwriteOnly%22%2C%22%40type%22%3A%22xsd%3Aboolean%22%7D%2C%22maximum%22%3A%7B%22%40id%22%3A%22jsonschema%3Amaximum%22%7D%2C%22minimum%22%3A%7B%22%40id%22%3A%22jsonschema%3Aminimum%22%7D%2C%22maxItems%22%3A%7B%22%40id%22%3A%22jsonschema%3AmaxItems%22%2C%22%40type%22%3A%22xsd%3AunsignedInt%22%7D%2C%22minItems%22%3A%7B%22%40id%22%3A%22jsonschema%3AminItems%22%2C%22%40type%22%3A%22xsd%3AunsignedInt%22%7D%2C%22contentEncoding%22%3A%7B%22%40id%22%3A%22jsonschema%3AcontentEncoding%22%2C%22%40type%22%3A%22xsd%3AunsignedInt%22%7D%2C%22minLength%22%3A%7B%22%40id%22%3A%22jsonschema%3AminLength%22%2C%22%40type%22%3A%22xsd%3AunsignedInt%22%7D%2C%22maxLength%22%3A%7B%22%40id%22%3A%22jsonschema%3AmaxLength%22%2C%22%40type%22%3A%22xsd%3AunsignedInt%22%7D%2C%22contentMediaType%22%3A%7B%22%40id%22%3A%22jsonschema%3AcontentMediaType%22%2C%22%40type%22%3A%22xsd%3Astring%22%7D%2C%22items%22%3A%7B%22%40id%22%3A%22jsonschema%3Aitems%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22required%22%3A%7B%22%40id%22%3A%22jsonschema%3Arequired%22%2C%22%40type%22%3A%22xsd%3Astring%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22enum%22%3A%7B%22%40id%22%3A%22jsonschema%3Aenum%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22const%22%3A%7B%22%40id%22%3A%22jsonschema%3Aconst%22%7D%2C%22multipleOf%22%3A%7B%22%40id%22%3A%22jsonschema%3AmultipleOf%22%7D%2C%22format%22%3A%7B%22%40id%22%3A%22jsonschema%3Aformat%22%7D%2C%22oneOf%22%3A%7B%22%40id%22%3A%22jsonschema%3AoneOf%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22allOf%22%3A%7B%22%40id%22%3A%22jsonschema%3AallOf%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22anyOf%22%3A%7B%22%40id%22%3A%22jsonschema%3AanyOf%22%2C%22%40container%22%3A%22%40set%22%7D%2C%22type%22%3A%7B%22%40id%22%3A%22rdf%3Atype%22%2C%22%40type%22%3A%22%40vocab%22%7D%2C%22title%22%3A%7B%22%40id%22%3A%22dct%3Atitle%22%7D%2C%22titles%22%3A%7B%22%40id%22%3A%22dct%3Atitle%22%2C%22%40container%22%3A%22%40language%22%7D%2C%22description%22%3A%7B%22%40id%22%3A%22dct%3Adescription%22%7D%2C%22descriptions%22%3A%7B%22%40id%22%3A%22dct%3Adescription%22%2C%22%40container%22%3A%22%40language%22%7D%2C%22object%22%3A%22jsonschema%3AObjectSchema%22%2C%22array%22%3A%22jsonschema%3AArraySchema%22%2C%22boolean%22%3A%22jsonschema%3ABooleanSchema%22%2C%22string%22%3A%22jsonschema%3AStringSchema%22%2C%22number%22%3A%22jsonschema%3ANumberSchema%22%2C%22integer%22%3A%22jsonschema%3AIntegerSchema%22%2C%22null%22%3A%22jsonschema%3ANullSchema%22%2C%22properties%22%3A%7B%22%40id%22%3A%22jsonschema%3Aproperties%22%2C%22%40container%22%3A%22%40index%22%2C%22%40index%22%3A%22jsonschema%3ApropertyName%22%7D%2C%22unit%22%3A%7B%22%40id%22%3A%22schema%3AunitCode%22%2C%22%40type%22%3A%22%40vocab%22%7D%7D%2C%22type%22%3A%22object%22%2C%22properties%22%3A%7B%22thingId%22%3A%7B%22type%22%3A%22string%22%7D%2C%22propertyId%22%3A%7B%22type%22%3A%22string%22%7D%7D%2C%22required%22%3A%5B%22thingId%22%2C%22propertyId%22%2C%22value%22%5D%7D%7D%5D%7D&context=%7B%22%40context%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Ftd%22%7D).

`jsonld.SyntaxError: Absolute IRI "xsd:string" confused with prefix "xsd".`

I am having trouble producing a minimal reproduction of this specific case though... It seems to only happen when I have a `https://www.w3.org/2019/wot/td#hasInputSchema` that makes use of the [JSON Schema in RDF](https://www.w3.org/2019/wot/json-schema#interpreting-json-schema-as-json-ld-1-1) inner context.

I will try to isolate this better, as I do have other use cases where using the JSON Schema in RDF context as an inner `@context` is functioning as expected.

Are `@type` identifiers processed the same way

**Comment by gkellogg** [comment]
It's falling afoul of logic in the Term Selection algorithm step 9 where it things that _var_ should be an IRI or IRI reference. Something is needed for this case, and it's odd that it didn't come up before now.

I'd say that this is a spec error with an unknown resolution at this time.

**Comment by vcharpenay** [comment]
> Replacing `"@index": "ex:name"` with `"@index": "http://example.org/ns/name"` in the compaction context solves the problem.

If the problem is roundtripping, it seems to me that there's another related problem in this example: when compacting with the full URI as index property, the result is as follows ([on the playground](https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%7B%22%40context%22%3A%7B%22ex%22%3A%22http%3A%2F%2Fexample.org%2Fns%2F%22%2C%22prop%22%3A%7B%22%40id%22%3A%22ex%3Aprop%22%2C%22%40container%22%3A%22%40index%22%2C%22%40index%22%3A%22ex%3Aname%22%7D%7D%2C%22prop%22%3A%7B%22foo%22%3A%7B%22%40id%22%3A%22ex%3Afoo%22%7D%2C%22bar%22%3A%7B%22%40id%22%3A%22ex%3Abar%22%7D%7D%7D&context=%7B%22%40context%22%3A%7B%22ex%22%3A%22http%3A%2F%2Fexample.org%2Fns%2F%22%2C%22prop%22%3A%7B%22%40id%22%3A%22ex%3Aprop%22%2C%22%40container%22%3A%22%40index%22%2C%22%40index%22%3A%22http%3A%2F%2Fexample.org%2Fns%2Fname%22%7D%7D%2C%22prop%22%3A%7B%22foo%22%3A%7B%22%40id%22%3A%22ex%3Afoo%22%7D%2C%22bar%22%3A%7B%22%40id%22%3A%22ex%3Abar%22%7D%7D%7D)):

```json
{
  "@context": {
    "ex": "http://example.org/ns/",
    "prop": {
      "@id": "ex:prop",
      "@container": "@index",
      "@index": "http://example.org/ns/name"
    }
  },
  "prop": {
    "@none": [
      {
        "@id": "ex:bar",
        "ex:name": "bar"
      },
      {
        "@id": "ex:foo",
        "ex:name": "foo"
      }
    ]
  }
}
```

The `@none` index key shouldn't be here. It's as if the index property is ignored when compacting.

**Comment by gkellogg** [comment]
Summary:

The value of `@index` on a property map can be a Compact IRI in addition to an IRI. The Compaction Algorithm is updated to first expand this value before re-compacting it. Added additional language to the Compaction Algorithm step 12.8.9.6.1 to first expand container key before compacting it.

**Comment by gkellogg** [comment]
@iherman this may or may not be considered an editorial change. Also, the description doesn't render properly in the errata doc.

**Comment by gkellogg** [comment]
I've updated my implementation and deployed it on the [Ruby RDF Distiller](http://rdf.greggkellogg.net/distiller).

**Comment by gkellogg** [comment]
On reflection, I believe this is a purely editorial change.
