### ISSUE TITLE
IRI compaction must not generate keyword-like relative IRIs

### ISSUE THREAD

**Issue by pchampin** [w3c/json-ld-api#524]
I noticed [a bug](https://github.com/digitalbazaar/jsonld.js/issues/435) which is present in at least 3 implementations. In these implementations, the result compacting the IRI `http://localhost/@special` against base `http://localhost/` is `@special`, which looks like a keyword. The consequence is that the resulted compact JSON-LD does not expand back to the original.

I think this deserves:
* a test-case
* a clarification in [6.2.IRI Compaction](https://www.w3.org/TR/json-ld11-api/#iri-compaction). I think a good way would be to insert a new step between 10 and 11, advising to prepend `./` to *var* if it has the form a keyword.

I will prepare a PR to that effect.

NB: I think this change can be considered editorial. It does not change the *intended* behavior of the algorithm.

**Comment by gkellogg** [comment]
Summary: Added wording in the IRI Compaction Algorithm to mitigate against compact IRIs that look like keywords.
