### ISSUE TITLE
Define a top-level @container as @type?

### ISSUE THREAD

**Issue by davidbarratt** [w3c/json-ld-api#526]
If I have an object like this:
```json
{
  "@context": "https://schema.org",
  "Person":  [
     {
       "name": "David"
     }
  ],
  "Country" : [
      {
        "code": "US"
      }
   ]
}
```
Is there a way to describe that this is a _type map_ at the top level? I  couldn't find a way to do this and the playground screams at me for attempting to override a keyword.

**Comment by gkellogg** [comment]
No; type maps are associated with terms, so you would need a top-level property who's values were the types. Something like the following:

```json
{
  "@context": ["https://schema.org", {
    "types": {"@id": "ex:types", "@container": "@type"}
  }],
  "types": {
    "Person":  [{"name": "David"}],
    "Country" : [{"code": "US"}]
  }
}
```

**Comment by davidbarratt** [comment]
Ah, ok cool. Thanks!
