### ISSUE TITLE
Reordered test by id

### ISSUE THREAD

**Issue by davidlehn** [w3c/json-ld-api#532]
I mistakenly pushed a patch to the main branch to reorder a test id.  I'm not sure what the process is in this case.  It's a simple patch but if it needs to be reverted, please speak up.
https://github.com/w3c/json-ld-api/commit/1c2a82eb42e08734dd4be420337e15124d9f8f88

Should the repo options be setup to not allow pushing direct to main?

**Comment by gkellogg** [comment]
I've accidentally done this too. I seem to have Admin access now, so I updated the policy to restrict direct pushes to main.

The change seems fine to me, so unless problems come up, I don't see a need to revert.
