### ISSUE TITLE
The algorithm for processing a reverse term returns too early

### ISSUE THREAD

**Issue by niklasl** [w3c/json-ld-api#565]
In section 4.2 [Create Term Definition](https://www.w3.org/TR/json-ld11-api/#create-term-definition) of the Context Processing Algorithms, step 13, processing a reverse term ends with:

> Set the term definition of term in active context to definition and the value associated with defined's entry term to true and return.

But with that early return, the algorithm stops processing a reverse term definition here, and thus reverse terms will not use any compaction features captured in the subsequent steps (step 19 and onward); e.g. indexed containers).

Thus this example:
```json
{
  "@context": {
    "@base": "https://example.org/",
    "@vocab": "https://example.net/ns#",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "statement": {"@reverse": "rdf:subject", "@container": "@index", "@index": "predicate"},
    "predicate": {"@id": "rdf:predicate", "@type": "@vocab"},
    "term": {"@id": "rdf:object", "@type": "@vocab"},
    "addedIn": {"@type": "@id"}
  },
  "@id": "/item/1",
  "statement": {
    "rdf:type": {"term": "A", "addedIn": "v1"}
  }
}
```
which *should* expand to:
```json
[
  {
    "@id": "https://example.org/item/1",
    "@reverse": {
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#subject": [
        {
          "https://example.net/ns#addedIn": [
            {
              "@id": "https://example.org/v1"
            }
          ],
          "http://www.w3.org/1999/02/22-rdf-syntax-ns#object": [
            {
              "@id": "https://example.net/ns#A"
            }
          ],
          "http://www.w3.org/1999/02/22-rdf-syntax-ns#predicate": [
            {
              "@id": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
            }
          ]
        }
      ]
    }
  }
]
```
instead results in:
```json
[
  {
    "@id": "https://example.org/item/1",
    "@reverse": {
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#subject": [
        {
          "https://example.net/ns#addedIn": [
            {
              "@id": "https://example.org/v1"
            }
          ],
          "http://www.w3.org/1999/02/22-rdf-syntax-ns#object": [
            {
              "@id": "https://example.net/ns#A"
            }
          ],
          "@index": "rdf:type"
        }
      ]
    }
  }
]
```

since the term definition of `statement` is missing what term to use when interpreting the `@index` value.

The fix is simple: remove "and return" from the end of step 13, and revise step 14 to begin with "Otherwise".

This is consistent with playground and distiller behaviour, and by looking at implementation, e.g. [the ruby implementation does not return early](https://github.com/ruby-rdf/json-ld/blob/3.2.3/lib/json/ld/context.rb#L605).

I have a fix for [TRLD](https://github.com/niklasl/trld/pull/3) to reflect the above (applying that, example output changed accordingly to the expected behaviour).

**Comment by pchampin** [comment]
FTR PyLD 2.0.3 also provides the expected result
