### ISSUE TITLE
Context processing step 5.8.3 vs expansion test c021

### ISSUE THREAD

**Issue by zoggy** [w3c/json-ld-api#567]
Hello,

Step 5.8.3 of context processing algorithm says:

> Otherwise, if value is an [IRI](https://tools.ietf.org/html/rfc3987#section-2) or [blank node identifier](https://www.w3.org/TR/rdf11-concepts/#dfn-blank-node-identifier), the [vocabulary mapping](https://www.w3.org/TR/json-ld11/#dfn-vocabulary-mapping) of result is set to the result of [IRI expanding](https://www.w3.org/TR/json-ld11-api/#dfn-iri-expanding) value using true for document relative . If it is not an [IRI](https://tools.ietf.org/html/rfc3987#section-2), or a [blank node identifier](https://www.w3.org/TR/rdf11-concepts/#dfn-blank-node-identifier), an [invalid vocab mapping](https://www.w3.org/TR/json-ld11-api/#dom-jsonlderrorcode-invalid-vocab-mapping) error has been detected and processing is aborted.

It is not clear what "it" in "If **it** is not an [IRI](https://tools.ietf.org/html/rfc3987#section-2), or a [blank node identifier](https://www.w3.org/TR/rdf11-concepts/#dfn-blank-node-identifier)," refers to:

- if it refers to `value`, then I think that the [expansion test 021](https://github.com/w3c/json-ld-api/blob/main/tests/expand/c021-in.jsonld) should fail as it defines a `ex:` vocab, which is not an IRI (`//` after `:` is missing) nor a blank node identifier.

- if it refers to the result of IRI-expansion, what must be done if `value` is not an IRI nor a blank node ?

Am I missing something ?

**Comment by gkellogg** [comment]
The term “it” does refer to the value. Note that the IRI scheme does not require “//l, this is only for hierarchical schemes, such as HTTP. Within the examples and tests, “ex:foo” is a valid IRI. (Look at `ipath-rootless` in [RFC3987](https://datatracker.ietf.org/doc/html/rfc3987#section-2.2)).

**Comment by zoggy** [comment]
Indeed. Thanks for your answer.

**Comment by TallTed** [comment]
@gkellogg — In https://github.com/w3c/json-ld-api/issues/567#issuecomment-1597332588, it's probably worth correcting `require “//l, this` to `require “//", this`.
