### ISSUE TITLE
Compaction test #t0108 contains duplicate keys in manifest and probably shouldn't

### ISSUE THREAD

**Issue by dclements** [w3c/json-ld-api#571]
Location: https://github.com/w3c/json-ld-api/blob/main/tests/compact-manifest.jsonld#L908

What is there:

```json
{
      "@id": "#t0108",
      "@type": ["jld:PositiveEvaluationTest", "jld:CompactTest"],
      "name": "Relative propererty IRIs with @vocab: ''",
      "purpose": "Complex use cases for relative IRI compaction or properties",
      "name": "context with JavaScript Object property names",
      "purpose": "Compact with context including JavaScript Object property names",
      "input": "compact/0108-in.jsonld",
      "context": "compact/0108-context.jsonld",
      "expect": "compact/0108-out.jsonld"
    },
```

Note the duplication of keys for `purpose` and `name`. Name looks like it should probably be "Relative property IRIs with @vocab: '' context for JavaScript Object property names" but purpose may not merge quite so easily. 

The [JSON RFC says](https://datatracker.ietf.org/doc/html/rfc8259): "The names within an object SHOULD be unique" and the [JSON-LD spec says](https://www.w3.org/TR/json-ld/#terms-imported-from-other-specifications) "In JSON-LD the names in an object must be unique," so it would seem this is an error in the manifest.

**Comment by gkellogg** [comment]
Yes, that's redundant information, and seems to be the result of a merge error. The later versions of these properties is what show up in the HTML version, and seem to be correct.

Looking at the inputs and outputs, they don't seem to have anything to do with Relative property IRis or `@vocab` (sic propererty) and do use property names compatible with JavaScript.
