### ISSUE TITLE
Mistake about `vocab` flag in IRI Expansion

### ISSUE THREAD

**Issue by helins** [w3c/json-ld-api#583]
The `IRI expanding` definition in `1.4.1 Algorithm Terms` mentions that the `vocab` flag defaults to `true` whereas the intro to the actual algorithm description in `5.2.2` mentions that "the two flags" should default to `false`.

**Comment by gkellogg** [comment]
Not a mistake; the default for the IRI Expansion Algorithm is, indeed, `false`; the IRI expanding term is like a macro, and in this case defaults to `true`. That leads to the tersest use of this term.

**Comment by helins** [comment]
Thanks @gkellogg, naming was a bit confusing but it makes sense 👍
