### ISSUE TITLE
Nested contexts behavior

### ISSUE THREAD

**Issue by davidlehn** [w3c/json-ld-api#590]
How should a nested context behave?
```json
{
  "@context": {
    "@context": {
      "p": "ex:p"
    }
  },
  "@id": "ex:1",
  "p": "value"
}
```
jsonld.js will [expand](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%7B%22%40context%22%3A%7B%22p%22%3A%22ex%3Ap%22%7D%7D%2C%22%40id%22%3A%22ex%3A1%22%2C%22p%22%3A%22value%22%7D) to:
```json
[
  {
    "@id": "ex:1",
    "ex:p": [
      {
        "@value": "value"
      }
    ]
  }
]
```
[Ruby Distiller](http://rdf.greggkellogg.net/distiller?command=expand&format=jsonld&output_format=jsonld) errors:
```
error
JSON::LD::JsonLdError::InvalidTermDefinition
invalid term definition: Term definition for "@context" has unexpected keys: p
```

[Sophia](https://perso.liris.cnrs.fr/pierre-antoine.champin/2023/sowasm/?noguess=&iformat=application%2Fld%2Bjson&oformat=application%2Fld%2Bjson&auto=&input=%7B%0A++%22%40context%22%3A+%7B%0A++++%22%40context%22%3A+%7B%0A++++++%22p%22%3A+%22ex%3Ap%22%0A++++%7D%0A++%7D%2C%0A++%22%40id%22%3A+%22ex%3A1%22%2C%0A++%22p%22%3A+%22value%22%0A%7D) errors:
```
Source failed: error while expanding: Expansion failed: Invalid context: Invalid term definition
```

If this isn't undefined behavior, there should be a positive or negative test for this case.

**Comment by gkellogg** [comment]
It is explicitly not allowed. Specific keywords in `@context` are called out in the context processing algorithm, everything else is a term definition. For a term definition `@type` is accounted for and no other keywords are allowed.

I suspect there are some tests for this, but maybe not for `@context`. I would be fine if such a negative test were added.

**Comment by davidlehn** [comment]
Added a test in #591.  I think 4.2.2.5 is the relevant spec text.  Looks like jsonld.js is recursively processing objects, and pulling out the `@context` data if present.  Works well to handle both regular context data and files with a `@context` key.  If this is an error, it does need a test.  I'm surprised this wasn't noticed before.

**Comment by davidlehn** [comment]
Addressed with test for correct behavior: https://github.com/w3c/json-ld-api/pull/591.
