### ISSUE TITLE
method to require {"id": "uri"} resource compaction result 

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-api#6]
__Issue:__ The compaction algorithm prefers the most compact format, which for resources without relationships is a string containing the URI.  This causes problems in systems that cannot handle arrays of mixed data types (for example ElasticSearch) when there are also resources that have relationships, resulting in both objects and strings in the same array.

For example:
```
"seeAlso": [
    "http://example.org/reference1",
    {"id": "http://example.org/reference2", "format": "text/html"}
  ]
```

would raise an error in Elastic.

__Proposed solution:__ Provide a flag to the compaction algorithm to signal that the resulting JSON should always create objects for resources, even if there is only the URI available.  This would instead render the example above as an array of objects:

```
"seeAlso": [
    {"id": "http://example.org/reference1"},
    {"id": "http://example.org/reference2", "format": "text/html"}
  ]
```

Original issue: [JSON-LD 1.1: method to require {"id": "uri"} resource compaction result #507](https://github.com/json-ld/json-ld.org/issues/507).

**Comment by gkellogg** [comment]
This may effectively be a duplicate of #3. No flags required.

**Comment by azaroth42** [comment]
Agreed. Let's leave both open until both are satisfied, hopefully by the same solution?

**Comment by azaroth42** [comment]
[WG resolved](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-08-31-json-ld#resolution5) that the use case for #3 and #6 are important, and should have a single solution to be discussed in a separate combined issue:  #33
