### ISSUE TITLE
toRdf() and flatten() API require extractAllScripts to default to true

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-api#603]
The JSON-LD section on [JSON-LD in HTML Documents](https://w3c.github.io/json-ld-syntax/#embedding-json-ld-in-html-documents) specifically says that all script all script elements are extracted, implying that the default value of |extractAllScripts| should be `true` for the `toRdf()` API entry point.

Tests for `flatten()` also say that it should extract all script elements, although there is no normative text to this effect.

Changing the behavior of `flatten()` would represent a change to the 1.1 behavior, but may be warranted.

The `toRdf()` entry point should be updated to say that the default is `true`.

**Comment by TallTed** [comment]
> The `toRdf()` entry point should be updated to say that the default if `true`.

Typo... ```default if `true` ``` -> ```default is `true` ```

**Comment by gkellogg** [comment]
<details>
<summary>Discussed on [today's call](https://json-ld.org/minutes/2024-07-10/#28)</summary>
<a id="link-topic-5.2" style="display:none;" href="#topic-5.2">✪</a></h2>
<div onmouseout="$('#link-28').hide()" onmouseover="$('#link-28').show()" id="28" class="information"><a href="https://github.com/w3c/json-ld-api/issues/603">https://github.com/w3c/json-ld-api/issues/603</a> -&gt; Issue 603 toRdf() and flatten() API require extractAllScripts to default to true (by gkellogg) [spec:enhancement] [needs discussion] [ErratumRaised] <a id="link-28" style="display:none;" href="#28">✪</a></div>
<div onmouseout="$('#link-29').hide()" onmouseover="$('#link-29').show()" id="29" class="comment"><span class="name">Anatoly Scherbakov</span>: Dlehn I wouldn&apos;t like to distract everyone as this is probably off-topic, but the issue I am facing now with python-yaml-ld is that I am redoing a lot of stuff that pyld already is doing. Basically, pyld already implements everything that&apos;s needed except a special DocumentLoader. So ideally, it feels like there shouldn&apos;t be a separate library for <a id="link-29" style="display:none;" href="#29">✪</a></div>
<div onmouseout="$('#link-30').hide()" onmouseover="$('#link-30').show()" id="30" class="comment"><span class="name">Anatoly Scherbakov</span>: YAML-LD at all, it should be just a feature of pyld. But in addition to that I would like to see improvements like pytest-based testing framework and better mypy/typing support. So I am still working on this as a separate implementation but it, kind of, feels wrong. <a id="link-30" style="display:none;" href="#30">✪</a></div>
<div onmouseout="$('#link-31').hide()" onmouseover="$('#link-31').show()" id="31" class="comment"><span class="name">Gregg Kellogg</span>:  Probably need to update the API to default to true, but unfortunate. <a id="link-31" style="display:none;" href="#31">✪</a></div>
<div onmouseout="$('#link-32').hide()" onmouseover="$('#link-32').show()" id="32" class="comment"><span class="name">Pierre-Antoine Champin</span>:  Do we have text which is inconsistent with tests? <a id="link-32" style="display:none;" href="#32">✪</a></div>
<div onmouseout="$('#link-33').hide()" onmouseover="$('#link-33').show()" id="33" class="comment"><span class="name">Pierre-Antoine Champin</span>: Sounds good to me <a id="link-33" style="display:none;" href="#33">✪</a></div>
<div onmouseout="$('#link-34').hide()" onmouseover="$('#link-34').show()" id="34" class="comment"><span class="name">Gregg Kellogg</span>:  My thought is to change API for toRDF but not flatten. <a id="link-34" style="display:none;" href="#34">✪</a></div>
<div onmouseout="$('#link-35').hide()" onmouseover="$('#link-35').show()" id="35" class="comment"><span class="name">Ted Thibodeau Jr.</span>:  I think tests are editable, if incorrect. <a id="link-35" style="display:none;" href="#35">✪</a></div>
<div class="comment-continuation">... We should fix the test suite, if its wrong.</div>
<div class="comment-continuation">... Implementations may need to be changed, but this should have been reported as a bug.</div>
<div onmouseout="$('#link-36').hide()" onmouseover="$('#link-36').show()" id="36" class="comment"><span class="name">Pierre-Antoine Champin</span>: That&apos;s what we have in rdf-canon: <a href="https://w3c.github.io/rdf-canon/spec/#h-note-3">https://w3c.github.io/rdf-canon/spec/#h-note-3</a> <a id="link-36" style="display:none;" href="#36">✪</a></div>
<div class="proposal"><strong>PROPOSAL:</strong>  update tests for flatten to assume extractAllScripts defaults to false. Update toRdf() API to set default for extractAllScripts to true.</div>
<div onmouseout="$('#link-37').hide()" onmouseover="$('#link-37').show()" id="37" class="comment"><span class="name">Gregg Kellogg</span>: +1 <a id="link-37" style="display:none;" href="#37">✪</a></div>
<div onmouseout="$('#link-38').hide()" onmouseover="$('#link-38').show()" id="38" class="comment"><span class="name">Anatoly Scherbakov</span>: +1 <a id="link-38" style="display:none;" href="#38">✪</a></div>
<div onmouseout="$('#link-39').hide()" onmouseover="$('#link-39').show()" id="39" class="comment"><span class="name">Ted Thibodeau Jr.</span>: +1 <a id="link-39" style="display:none;" href="#39">✪</a></div>
<div onmouseout="$('#link-40').hide()" onmouseover="$('#link-40').show()" id="40" class="comment"><span class="name">Pierre-Antoine Champin</span>: +1 <a id="link-40" style="display:none;" href="#40">✪</a></div>
<div onmouseout="$('#link-41').hide()" onmouseover="$('#link-41').show()" id="41" class="comment"><span class="name">Niklas Lindstr&#246;m</span>: +0 (Haven&apos;t thought it through fully) <a id="link-41" style="display:none;" href="#41">✪</a></div>
<div onmouseout="$('#link-42').hide()" onmouseover="$('#link-42').show()" id="42" class="comment"><span class="name">David I. Lehn</span>: +0 <a id="link-42" style="display:none;" href="#42">✪</a></div>
<div onmouseout="$('#link-43').hide()" onmouseover="$('#link-43').show()" id="43" class="comment"><span class="name">Niklas Lindstr&#246;m</span>: Probably makes sense; so +ITY ;) <a id="link-43" style="display:none;" href="#43">✪</a></div>
<div onmouseout="$('#link-res-1').hide()" onmouseover="$('#link-res-1').show()" id="resolution-1" class="resolution">
<a id="link-res-1" style="display:none;" href="#resolution-1">✪</a></div>
</details>
<strong>RESOLUTION:</strong> update tests for flatten to assume extractAllScripts defaults to false. Update toRdf() API to set default for extractAllScripts to true.

**Comment by gkellogg** [comment]
Summary: Explicitly set the default value for `extractAllScripts` to `true` in `toRdf()`.
