### ISSUE TITLE
Allow processing model of @type to be customized

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-api#7]
I think the root cause of the issue is that `@type` has its processing model constrained by the specification, rather than by interpreting the context (and hence `@vocab`). As @dlongley says, it's compacting to a relative URL rather than a prefixed compact IRI.  

Is anyone willing to propose changing the definition of `@type`? Otherwise I think we have to close the issue as `wontfix`.

Original issue: [precedence of @vocab for compaction too strong? #526](https://github.com/json-ld/json-ld.org/issues/526).

**Comment by dlongley** [comment]
I don't think we should change this. My opinion is `wontfix`.

**Comment by gkellogg** [comment]
If we've opened the door for `@type` to have `@container: @set`, then we might open it to have `@vocab: null` as well, but this seems like a can of worms, and only serves to make the language more complicated, so I also support `wontfix`

**Comment by azaroth42** [comment]
[Resolution](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-08-17-json-ld#resolution5) on WG call of 2018-08-17: Close won't fix.  The use case can now be accomplished with longer, scoped contexts and the precedence has other ramifications beyond this particular scenario.
