### ISSUE TITLE
Create Term Definition use of Context Processing algorithm is inconsistent

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-api#99]
The [Create Term Definition](https://w3c.github.io/json-ld-api/#create-term-definition) algorithm, in item 22.3 says:

> Invoke the Context Processing algorithm using the active context, context as local context, and true for from property. If any error is detected, an invalid scoped context error has been detected and processing is aborted.

The wording here suggests that the active context will be updated in place (there is no talk of any return values from the "Context Processing algorithm"). This seems to be inconsistent with both the description of the [Context Processing algorithm](https://w3c.github.io/json-ld-api/#context-processing-algorithm) (which talks about cloning the supplied active context and ends with an explicit `return`) and with other uses of the algorithm, such as the [Expansion Algorithm](https://w3c.github.io/json-ld-api/#expansion-algorithm) item 6:

> set active context to the result of the Context Processing algorithm, passing active context and the value of the @context member as local context.

I don't think the Create Term Definition algorithm can update the active context in-place, as that would suggest that changes here would escape into outer scopes, in particular other iterations of the 4.9 loop body in the Context Processing Algorithm.

**Comment by gkellogg** [comment]
> The [Create Term Definition](https://w3c.github.io/json-ld-api/#create-term-definition) algorithm, in item 22.3 says:
> 
> > Invoke the Context Processing algorithm using the active context, context as local context, and true for from property. If any error is detected, an invalid scoped context error has been detected and processing is aborted.
> 
> The wording here suggests that the active context will be updated in place (there is no talk of any return values from the "Context Processing algorithm"). This seems to be inconsistent with both the description of the [Context Processing algorithm](https://w3c.github.io/json-ld-api/#context-processing-algorithm) (which talks about cloning the supplied active context and ends with an explicit `return`) and with other uses of the algorithm, such as the [Expansion Algorithm](https://w3c.github.io/json-ld-api/#expansion-algorithm) item 6:

The purpose of doing the context processing is to detect errors. The context does not actually become the active context until its encountered when expanding or compacting. A note that the context is processed for determining validity only here may be in order.

> > set active context to the result of the Context Processing algorithm, passing active context and the value of the @context member as local context.
> 
> I don't think the Create Term Definition algorithm can update the active context in-place, as that would suggest that changes here would escape into outer scopes, in particular other iterations of the 4.9 loop body in the Context Processing Algorithm.

In fact, the algorithm introduction says that it does update the active context:

> This algorithm is called from the Context Processing algorithm to create a term definition in the active context for a term being processed in a local context.

However, it's called from the context processing algorithm which creates a new context _result_ and passes this to the create term definition algorithm to use as its _active context_. So, while it's updating the active context, it won't leak out to other uses.

**Comment by kasei** [comment]
> The purpose of doing the context processing is to detect errors. The context does not actually become the active context until its encountered when expanding or compacting. A note that the context is processed for determining validity only here may be in order.

Ah! Knowing that its sole purpose it checking for errors would indeed help change how I read it. A note about that would be great; perhaps also mentioning that the result of the invocation is discarded?

**Comment by kasei** [comment]
> However, it's called from the context processing algorithm which creates a new context _result_ and passes this to the create term definition algorithm to use as its _active context_. So, while it's updating the active context, it won't leak out to other uses.

Are there any concerns with modifying _result_ in-place in the context processing algorithm, but doing so in a non-deterministic way? (The loop in 4.9 does not seem to define an ordering as some other loops in the API document do.)

**Comment by gkellogg** [comment]
We've been trying to go away from explicit ordering where possible or make it an option. As term definitions are processed from a dictionary, each term definition will be unique, so I don't see where random ordering of terms is non-deterministic. The only place this is the case is where a term definition depends on another because of the use of compact IRI prefixes. Code in the IRI Expansion algorithm will recursively call Create Term Definition which specifically allows for this.

**Comment by gkellogg** [comment]
@kasei see if that does it for this issue.

**Comment by kasei** [comment]
@gkellogg Thanks. That looks much better! I added one comment on the commit about possible room for another small improvement to the wording.
